---
- name: wpasupplicant set service on nodes
  hosts: nodes
  become: True
  gather_facts: False

  tasks:
  # tasks file for wpasupplicant
  - name: ensure wpasupplicant installed
    apt:
      name: '{{ wpasupplicant__pkg_name }}'
      state: present
      update_cache: '{{ wpasupplicant__pkg_update_cache }}'

  - name: Stop and disable wpasupplicant
    systemd:
      name: '{{ wpasupplicant__service }}'
      state: "{{ wpasupplicant__state }}"
      enabled: "{{ wpasupplicant__enabled }}"
      masked: "{{ wpasupplicant__masked }}"
