// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Clustering_Guide.asciidoc
    for authors, copyright and license information.

////

* You have at least three (3) installed PacketFence (v7+) servers
* The servers are running one of RHEL 8 / Debian 11
* The servers have identical identifiers for network interfaces (e.g. eth0) (see next section)
* The servers must have IPv6 disabled (see next section)
* The servers must have a fully qualified domain name (FQDN) to identify them
* The servers are located within the following latency limits (requirement for Galera cluster)
 * For smaller deployments, 75ms of latency can be tolerated between the cluster nodes
 * For larger deployments, 50ms of latency can be tolerated between the cluster nodes
 * PacketFence does support external MySQL primary/replicas to allow deployments which are geo distributed (see 'Geo Distributed Database' in this document for details)

NOTE: Appended to this guide is a glossary on specialized terms used in this document.

