// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Clustering_Guide.asciidoc
    for authors, copyright and license information.

////

//== Troubleshooting a cluster

=== Checking the MariaDB sync

In order to check the MariaDB sync, you can look at the status of the `wsrep` status values inside MariaDB.

----
MariaDB> show status like 'wsrep%';
----

Important variables:

  * `wsrep_cluster_status`: Display whether or not the node is part of a primary view or not. A healthy cluster should always show as primary
  * `wsrep_incoming_addresses`: The current members of the cluster. All the nodes of your cluster should be listed there.
  * `wsrep_last_committed`: Sequence number of the most recently committed transaction. You can identify the most advanced node with this value.
  * `wsrep_local_state_comment`: Current sync state of the cluster. A healthy state is 'Synced'. Refer to the Galera cluster documentation for the meaning of the other values this can have.

In order for the cluster to be considered healthy, all nodes must be listed under `wsrep_incoming_addresses` and `wsrep_local_state_comment` must be `Synced`. Otherwise look in the MariaDB log ([filename]`/usr/local/pf/logs/mariadb_error.log`)

=== Automatic clustering resolution issue: galera-autofix service

Since v10, the `galera-autofix` service will try to resolve automatically issues on Galera clusters.

On a cluster which has an issue, once all nodes are back online, you should wait:

* around 10 minutes when at least one of the nodes of the cluster is able to offer database service
* around 20 minutes when there is no database service available

If your cluster still have issue after that time, you can try to solve it manually by looking at sections below.

=== Cluster offer database service without all nodes

When at least one of the nodes of the cluster is able to offer database
service, you can apply the following commands on a broken node to rejoin it to
the cluster:

[source,bash]
----
systemctl stop packetfence-mariadb
systemctl stop packetfence-galera-autofix
rm -fr /var/lib/mysql/*
systemctl start packetfence-mariadb
systemctl start packetfence-galera-autofix
----

This action will not cause service disruption on current cluster.

After all nodes have joined back cluster, you can verify <<_checking_the_mariadb_sync,MariaDB sync>>.

=== No more database service

When there is no more database service in your cluster, you need to do a full recovery.

You must stop the node you wish to keep the data from and start it with the
`--force-new-cluster` option. You can identify which node has the most recent
data by looking at value of `seqno` in `/var/lib/grastate.dat`. Then apply
following commands on that node:

[source,bash]
----
systemctl stop packetfence-mariadb
systemctl stop packetfence-galera-autofix
/usr/local/pf/sbin/pf-mariadb --force-new-cluster
----

==== On each of the discarded servers

First, stop `packetfence-mariadb` and `packetfence-galera-autofix` on *all*
the servers you want to discard data from.

[source,bash]
----
systemctl stop packetfence-mariadb
systemctl stop packetfence-galera-autofix
----

On each of the servers you want to discard the data from, you must destroy all
the data in `/var/lib/mysql` and start `packetfence-mariadb` so it resyncs its
data from scratch.

[source,bash]
----
rm -fr /var/lib/mysql/*
systemctl start packetfence-mariadb
----

You should then see `/var/lib/mysql` be populated again with the data and once
MariaDB becomes available again on the server, it means the sync has
completed. In case of issues, look in the MariaDB log file
(`/usr/local/pf/logs/mariadb_error.log`)

==== On node started with --force-new-cluster

If you were performing a full recovery, you should now break the
`--force-new-cluster` command and start `packetfence-mariadb`
normally using:

[source,bash]
----
systemctl start packetfence-mariadb
----

==== On all servers

When your database offers service again, you can restart
`packetfence-galera-autofix` service using:

[source,bash]
----
systemctl start packetfence-galera-autofix
----

Be sure to verify <<_checking_the_mariadb_sync,MariaDB sync>>.
