---
roles:
  - src: inverse_inc.gitlab_buildpkg_tools
    version: v1.3.5
  - src: geerlingguy.nodejs
    version: 6.0.0

collections:
  - name: inverse_inc.utils
  - name: debops.debops
  - name: community.general
    version: 7.0.1
