---
- import_playbook: playbooks/install_utils.yml

- import_playbook: playbooks/register_rhel_subscription.yml

- import_playbook: playbooks/upgrade_os.yml

- import_playbook: playbooks/install_repos.yml

- import_playbook: playbooks/install_pf_centos.yml
