#!/bin/bash

source /usr/local/pfconnector-remote/containers/systemd-service

name=pfconnector-remote

args=$(base_args "${name}")
args="$args --env-file /usr/local/pfconnector-remote/conf/pfconnector-client.env"
args="$args -eLOG_OUTPUT=stdout"
args="$args -v /usr/local/pfconnector-remote/conf:/usr/local/pf/conf"
args="$args -v /usr/local/pfconnector-remote/logs:/usr/local/pf/logs"
args="$args -v /usr/local/pfconnector-remote/var/conf:/usr/local/pf/var/conf"
args="$args --network host"

run "$name" "$args" "/usr/local/pf/sbin/pfconnector client ENV 127.0.0.1:22226:127.0.0.1:22226 100.64.0.1:22226:127.0.0.1:22226"
