#!/bin/bash

source /usr/local/pfconnector-remote/containers/systemd-service

name=pfconnector-remote-combined

args=`base_args $name`

# pfconnector-client env vars
args="$args --env-file /usr/local/pfconnector-remote/conf/pfconnector-client.env"
args="$args -eLOG_OUTPUT=stdout"

# Shared mounts
args="$args -v /usr/local/pfconnector-remote/conf:/usr/local/pf/conf"
args="$args -v /usr/local/pfconnector-remote/logs:/usr/local/pf/logs"
args="$args -v /usr/local/pfconnector-remote/var/conf:/usr/local/pf/var/conf"

# radiusd-auth mounts
args="$args -v /usr/local/pfconnector-remote/conf/system_init_key:/usr/local/pf/conf/system_init_key"
args="$args -v /usr/local/pfconnector-remote/conf/log.conf.d/:/usr/local/pf/conf/log.conf.d/"
args="$args -v /usr/local/pfconnector-remote/conf/ssl/:/usr/local/pf/conf/ssl/"
args="$args -v /usr/local/pfconnector-remote/raddb/:/usr/local/pf/raddb/"

args="$args --network=host"

run $name "$args"
