#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=radiusd-auth

set -a
. /usr/local/pf/var/conf/$name.env
set +a

args=`base_args $name`
args="$args -v /usr/local/pf/conf/system_init_key:/usr/local/pf/conf/system_init_key"
args="$args -v /usr/local/pf/conf/log.conf.d/:/usr/local/pf/conf/log.conf.d/"
args="$args -v /usr/local/pf/conf/ssl/:/usr/local/pf/conf/ssl/"
args="$args -v /usr/local/pf/raddb/:/usr/local/pf/raddb/"
args="$args -v /usr/local/pf/logs/:/usr/local/pf/logs/"
args="$args -p $RADIUSD_LISTEN_PORT:$RADIUSD_LISTEN_PORT/udp"
args="$args $(domain_args)"
args="$args --network=host"

run $name "$args"
