#!/bin/bash

source /usr/local/pfconnector-remote/containers/systemd-service

name=radiusd-auth

args=`base_args $name`
args="$args -v /usr/local/pfconnector-remote/conf/system_init_key:/usr/local/pf/conf/system_init_key"
args="$args -v /usr/local/pfconnector-remote/conf/log.conf.d/:/usr/local/pf/conf/log.conf.d/"
args="$args -v /usr/local/pfconnector-remote/conf/ssl/:/usr/local/pf/conf/ssl/"
args="$args -v /usr/local/pfconnector-remote/raddb/:/usr/local/pf/raddb/"
args="$args -v /usr/local/pfconnector-remote/logs/:/usr/local/pf/logs/"
args="$args --network=host"

run $name "$args"
