#!/bin/bash

source /usr/local/pfconnector-remote/containers/systemd-service

name=radiusd-auth

set -a
. /usr/local/pfconnector-remote/var/conf/$name.env
set +a

args=`base_args $name`
args="$args -v /usr/local/pfconnector-remote/conf/system_init_key:/usr/local/pfconnector-remote/conf/system_init_key"
args="$args -v /usr/local/pfconnector-remote/conf/log.conf.d/:/usr/local/pfconnector-remote/conf/log.conf.d/"
args="$args -v /usr/local/pfconnector-remote/conf/ssl/:/usr/local/pfconnector-remote/conf/ssl/"
args="$args -v /usr/local/pfconnector-remote/raddb/:/usr/local/pfconnector-remote/raddb/"
args="$args -v /usr/local/pfconnector-remote/logs/:/usr/local/pfconnector-remote/logs/"
args="$args -p $RADIUSD_LISTEN_PORT:$RADIUSD_LISTEN_PORT/udp"
args="$args $(domain_args)"
args="$args --network=host"

run $name "$args"
