- hosts: pfservers
  name: install pf on standalone
  become: True
  collections:
    - inverse_inc.packetfence

  # search roles in collections
  roles:

    - role: packetfence_common
      tags: install

    - role: packetfence_install
      tags: install

  ###
  # Specific task related to Vagrant management
  ###
  # We use another interface than the default as management
  # it's possible to do this until current SSH session has not been cut
  
  tasks:
    - name: allow ssh on default interface for vagrant management
      blockinfile:
        path: "{{ packetfence_install__conf_dir }}/iptables.conf"
        block: |
          # allow SSH for vagrant management
          -A INPUT --in-interface {{ ansible_default_ipv4['interface'] }} --jump ACCEPT
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: "-A INPUT --in-interface lo --jump ACCEPT"
      register: install_pf_iptables_register_vagrant_rule

# because we skip configurator for stable_and_nightly
# iptables need to be restarted to take previous change into account
# drawkbacks:
# - impossible to reuse packetfence__install variables
# - not perfect to rely on a register set in another play
- hosts: stable_and_nightly
  name: restart iptables
  become: True

  tasks:
    - name: apply new iptables rule for vagrant management
      command: "/usr/local/pf/bin/pfcmd service iptables restart"
      when: install_pf_iptables_register_vagrant_rule is changed
      
