---
# versions in roles should be equals to tags
roles:
  - src: inverse_inc.gitlab_buildpkg_tools
    version: v1.3.1

# For roles, to test locally with Vagrant (due to --force option)
# Ansible will create an export, not a symlink to git repository
  # - src: file:///home/nqb/git/inverse-inc.gitlab-buildpkg-tools/.git
  #   scm: git
  #   name: inverse_inc.gitlab_buildpkg_tools
  #   version: feature/priority

collections:
  - name: inverse_inc.packetfence
    version: 1.2.0
  - name: debops.debops
    version: 2.3.2
  - name: inverse_inc.windows
    version: 1.0.2
  - name: inverse_inc.cumulus
    version: 1.1.1
  - name: inverse_inc.utils
    version: 1.1.1
  - name: inverse_inc.wireless
    version: 0.2.2

# For collections, to test locally with Vagrant (due to --force option)
# Ansible will create an export, not a symlink to git repository
  # - name: file:///home/nqb/git/ansible-packetfence/.git
  #   type: git
  #   version: feature/my-branch

# to test using a Git repository
  # - name: https://github.com/inverse-inc/ansible-packetfence.git
  #   type: git
  #   version: feature/rhel8
