---
- name: Install Venom
  hosts: [ 'service_venom' ]
  gather_facts: False
  become: True
  collections:
    - inverse_inc.packetfence

  roles:
    - role: venom
      tags: venom
      when: lookup("env", "INTEGRATION_TESTS") == 'yes'
