
This guide summarizes the installation of the pfconfig service.
---------------------------------------------------------------

First, make sure pfconfig has the executable bit on.
# ll /usr/local/pf/sbin/pfconfig

Now go in the pf directory
# cd /usr/local/pf

Next install the init file on the system (only for RHEL based systems).
# cp addons/pfconfig/pfconfig.init /etc/init.d/pfconfig
# chmod +x /etc/init.d/pfconfig

Now, unmanage memcached from PacketFence by adding this to pf.conf
[services]
memcached=disabled

Now, install the memcached init script provided (only for RHEL based systems)
# cp addons/pfconfig/memcached.init /etc/init.d/memcached
# chmod +x /etc/init.d/memcached

Stop PacketFence completely
# service packetfence stop

Start memcached and set it on for boot
# service memcached start
# chkconfig memcached on

Start pfconfig and set it on for boot
# service pfconfig start
# chkconfig pfconfig on

Test the pfconfig service
addons/pfconfig/cmd.pl get config::Switch

Start PacketFence
# service packetfence start


