- hosts: pfservers
  name: install pf on standalone
  become: True
  collections:
    - inverse_inc.packetfence

  # search roles in collections
  roles:

    - role: packetfence_common
      tags: common

    - role: packetfence_install
      tags: install

  ###
  # Specific tasks related to Vagrant management
  ###
  # We use another interface than the default as management
  # it's possible to do this until current SSH session has not been cut  
  tasks:
    - import_tasks: tasks/vagrant_firewalld.yml
      tags: firewalld

    # packetfence-test need to be installed
    - import_tasks: tasks/install_venom_local_vars.yml
      tags: venom_vars
