#!/bin/bash

LOCAL_REGISTRY=local
source /usr/local/pf/conf/build_id

function base_args {
  name="$1"
  args="--sig-proxy=true --rm --name=$name --add-host=containers-gateway.internal:host-gateway"

  args="$args -v /var/lib/mysql:/var/lib/mysql"
  args="$args -v /usr/local/fingerbank/db:/usr/local/fingerbank/db"

  if [ -f /usr/local/pf/var/conf/$name.env ]; then
    args="$args --env-file /usr/local/pf/var/conf/$name.env"
  fi

  echo "$args"
}

function build_run {
  name="$1"
  args="$2"
  cd /usr/local/pf/
  img=$(docker build --build-arg=KNK_REGISTRY_URL=$LOCAL_REGISTRY --build-arg=IMAGE_TAG=$TAG_OR_BRANCH_NAME -q -f containers/$name/Dockerfile .)
  run_img $img $name "$args"
}

function run {
  name="$1"
  args="$2"
  img=$LOCAL_REGISTRY/$name:$TAG_OR_BRANCH_NAME
  run_img $img $name "$args"
}

function run_img {
  img="$1"
  name="$2"
  args="$3"
  cd /usr/local/pf/
  docker container rm -f $name
  echo "Running with args $args"
  docker run $args --name=$name $img
}
