// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Network_Devices_Configuration_Guide.asciidoc
    for authors, copyright and license information.

////

//== Wireless Controllers and Access Point Configuration


=== Assumptions

Network infrastructure assumptions for this configuration:

[options="compact"]
* PacketFence fully configured with FreeRADIUS running
* PacketFence IP address: 192.168.1.5
* Normal VLAN: 1
* Registration VLAN: 2
* Isolation VLAN: 3
* MAC Detection VLAN: 4
* Guest VLAN: 5
* VoIP, Voice VLAN: 100
* use SNMP v2c
* SNMP community name: public
* RADIUS Secret: useStrongerSecret footnote:[Be careful to change the secret key to a much stronger one. A 16 character random secret with digits, upper case and lower case characters is recommended.]
* Open SSID: PacketFence-Public
* WPA-Enterprise SSID: PacketFence-Secure


=== Unsupported Equipment

Wireless network access configuration is more consistent between vendors due to
standardization compared to wired side: VLAN assignment done centrally with
RADIUS and consistent client protocol (MAC-Authentication or 802.1X).

This consistency means most wireless network devices work out-of-the-box with
PacketFence. Only missing piece typically: remote client deauthentication for
VLAN assignment (deauth user to reconnect and get new VLAN).

Even if your wireless equipment isn't explicitly supported by PacketFence, try
it. Next section covers objectives for testing equipment without existing
configuration.

Here are the high-level requirements for proper wireless integration with
PacketFence

[options="compact"]
* The appropriate VLANs must exist
* Allow controller to honor VLAN assignments from AAA (sometimes called AAA override)
* Put your open SSID (if any) in MAC-Authentication mode and authenticate against the FreeRADIUS hosted on PacketFence
* Put your secure SSID (if any) in 802.1X mode and authenticate against FreeRADIUS hosted on PacketFence.
* On registration / isolation VLANs the DHCP traffic must reach the PacketFence server
* On your production VLANs a copy of the DHCP traffic must reach PacketFence where a pfdhcplistener listens (configurable in `pf.conf` under `interfaces`)

At this point, user registration with the captive-portal is possible and
registered users should have access to the appropriate VLANs. However, VLAN
changes (like after a registration) won't automatically happen, you will need to
disconnect / reconnect. An explanation is provided in introduction section above
about this behavior.

You can try modules similar to your equipment if any (read appropriate
instructions) or you can try to see if RFC3576 is supported. RFC3576 covers
RADIUS Packet of Disconnect (PoD) also known as Disconnect Messages (DM) or
Change of Authorization (CoA). You can try the Aruba module if you want to
verify if RFC3576 is supported by your hardware.

If none of the above worked then you can fallback to inline enforcement or let
us know what equipment you are using on the
https://lists.sourceforge.net/lists/listinfo/packetfence-devel[packetfence-devel mailing list].

=== Aerohive Networks

include::networkdevice/aerohive.asciidoc[]

[float]
===== Roles (User Profiles)

Since PacketFence 3.3, we now support user profiles on the AeroHIVE hardware.
To build a User Profile, go to _Configuration -> User Profiles_, and create what
you need. When you define the switch
definition in PacketFence, the role will match the User Profile attribute
number. Example

   roles=CategoryStudent=1;CategoryStaff=2

And in the AeroHIVE configuration, you have :

   StudentProfile attribute number 1
   StaffProfile attribute number 2

Last step is to allow the User Profile to be returned for a particular SSID. Go
to _Configuration -> SSIDs -> Your_SSID -> User Profiles_ for Traffic
Management*, and select the User Profiles you will
return for the devices.

In version 6 or later of the HiveOS, we do return VLAN ID matching the number
that the *User Profile* has. Create your *User Profile* in the HiveManager as
usual, assign the matching VLAN, and in PacketFence configuration add the wanted
VLAN ID in the section *Roles by VLAN*.

=== Anyfi Networks

include::networkdevice/anyfi.asciidoc[]

=== Avaya

==== Wireless Controller

NOTE: To be contributed....

=== Aruba

include::networkdevice/aruba.asciidoc[]

=== Belair Networks (now Ericsson)

include::networkdevice/belair_networks_ericsson.asciidoc[]

=== Bluesocket

include::networkdevice/bluesocket.asciidoc[]


=== Brocade

==== RF Switches

See the <<_motorola,Motorola RF Switches>> documentation.

=== Cambium

include::networkdevice/cambium.asciidoc[]

=== Cisco

include::networkdevice/cisco_ap.asciidoc[]

=== CoovaChilli

include::networkdevice/coovachilli.asciidoc[]

=== D-Link

==== DWL Access-Points and DWS 3026

NOTE: To be contributed...

=== Extreme Networks

include::networkdevice/extreme_networks_wireless.asciidoc[]

=== Extricom

include::networkdevice/extricom.asciidoc[]

=== Fortinet FortiGate

include::networkdevice/fortinet_fortigate.asciidoc[]

=== Hostapd

include::networkdevice/hostapd.asciidoc[]

=== Huawei

include::networkdevice/huawei_ap.asciidoc[]

=== Meraki

include::networkdevice/meraki.asciidoc[]

=== Mikrotik

include::networkdevice/mikrotik.asciidoc[]

=== HP

==== ProCurve Controller MSM710

  To be contributed...

=== Intelbras

==== AP3620

General Radius:

  dot1x authentication-method eap
   
  radius scheme packetfence
   primary authentication 192.168.1.5
   primary accounting 192.168.1.5
   key authentication simple useStrongerSecret
   key accounting simple useStrongerSecret
   user-name-format without-domain
  
  radius dynamic-author server
   client ip 192.168.1.5 key simple useStrongerSecret
  
  domain packetfence
   authentication default radius-scheme packetfence
   authorization default radius-scheme packetfence
   accounting default radius-scheme packetfence
   
  interface WLAN-Radio1/0/2
   service-template pf-secure
   service-template pf-open
   max-power 22
   channel band-width 20
  
Secure 802.1x SSID:

  wlan service-template pf-secure
  	 ssid PF-Secure
  	 akm mode dot1x
  	 cipher-suite ccmp
  	 security-ie rsn
  	 client-security authentication-mode dot1x
  	 dot1x domain dot1x
  	 bss transition-management enable
  	 service-template enable
  
Open Mac-Authentication SSID:

  wlan service-template pf-open
  	description Captive portal authentication
  	ssid !PF-Open
  	client-security authentication-mode mac
  	mac-authentication domain packetfence
  	service-template enable
  
=== Meru

include::networkdevice/meru.asciidoc[]

=== Mojo Networks

include::networkdevice/mojo_networks.asciidoc[]

=== Motorola

include::networkdevice/motorola.asciidoc[]

=== Ruckus

include::networkdevice/ruckus.asciidoc[]

=== Ruckus SmartZone

include::networkdevice/ruckus_smartzone.asciidoc[]

=== Ruckus Unleashed

include::networkdevice/ruckus_unleashed.asciidoc[]

=== Trapeze

include::networkdevice/trapeze.asciidoc[]

=== Ubiquiti

include::networkdevice/ubiquiti_ap.asciidoc[]

=== Xirrus

include::networkdevice/xirrus.asciidoc[]
