/config/device_registration/{device_registration_id}:
  delete:
    deprecated: true
    description: Remove an item
    operationId: api.v1.Config::DeviceRegistrations.remove
    parameters:
    - in: path
      name: device_registration_id
      required: true
      schema:
        type: string
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::DeviceRegistrations
  get:
    deprecated: true
    description: Get an item
    operationId: api.v1.Config::DeviceRegistrations.get
    parameters:
    - in: path
      name: device_registration_id
      required: true
      schema:
        type: string
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfigDeviceRegistration'
        description: Item
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    deprecated: true
    description: Update an item
    operationId: api.v1.Config::DeviceRegistrations.update
    parameters:
    - in: path
      name: device_registration_id
      required: true
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigDeviceRegistration'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    deprecated: true
    description: Replace an item
    operationId: api.v1.Config::DeviceRegistrations.replace
    parameters:
    - in: path
      name: device_registration_id
      required: true
      schema:
        type: string
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConfigDeviceRegistration'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
