#!/usr/bin/bash

user=$(whoami)
if [ $# -eq 0 ]; then
	path=$(realpath ~/packetfence)
	echo "usage: $(basename "$0") [/path/to/packetfence]"
else
	path=$(realpath $1)
fi

hosts=$(yq -r ".all.vars.users_vars.$user.vms | keys | .[]" $path/addons/vagrant/inventory/hosts | grep '^pf.*$')
declare -A ips
for host in $hosts; do
	ips[$host]=$(yq -r ".all.vars.users_vars.$user.vms.$host.ip" $path/addons/vagrant/inventory/hosts)
done

echo "watching $path"
while true; do
 	inotifywait -r -e modify,attrib,close_write,move,create,delete $path/t/venom
	for host in $hosts; do
		if ping -c 1 ${ips[$host]} &> /dev/null; then
			echo "=========================="
			echo "rsync with $host/$ip[$host]"
			echo "=========================="
			rsync -avz --exclude="*.swp" --exclude="vars/local.yml" --rsync-path="sudo rsync" -e "ssh" $path/t/venom/ ${ips[$host]}:/usr/local/pf/t/venom/
		fi
	done
done
