#! /busybox/sh
# Taken from https://gitlab.com/Orange-OpenSource/gitlab-buildpkg
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -o nounset -o pipefail -o errexit

echo $IMAGE_NAME
DOCKFILE_PATH=$CI_PROJECT_DIR/docker/$IMAGE_NAME/Dockerfile
IMAGE_DEST="${CI_REGISTRY_IMAGE}/${IMAGE_NAME}:${IMAGE_TAG}"
env | grep CI_

echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

[ -d dockertmp ] || mkdir dockertmp
cp $DOCKFILE_PATH dockertmp/${IMAGE_NAME}

/kaniko/executor --context $CI_PROJECT_DIR --dockerfile dockertmp/${IMAGE_NAME} --destination ${IMAGE_DEST}

