#!/bin/bash

PF_REGISTRY=local
PF_VERSION=11.3
GO_VERSION=1.17

function base_args {
  name="$1"
  args="--sig-proxy=true --rm --name=$name --add-host=host.docker.internal:host-gateway"

  args="$args -v /var/lib/mysql:/var/lib/mysql"
  args="$args -v /usr/local/fingerbank/db:/usr/local/fingerbank/db"

  echo "$args"
}

function run {
  name="$1"
  args="$2"
  cd /usr/local/pf/
  docker container rm -f $name
  echo "Running with args $args"
  docker run $args --name=$name $(docker build --build-arg=KNK_REGISTRY_URL=$PF_REGISTRY --build-arg=IMAGE_TAG=$PF_VERSION --build-arg=GO_VERSION=$GO_VERSION -q -f docker/$name/Dockerfile .)
}
