Message:
  type: object
  properties:
    message:
      description: A meaninful user readable message about what happened
      type: string
      
ErrorsWithMessage:
  type: object
  properties:
    message:
      type: string
    errors:
      type: array
      items:
        type: object
      
Iterable:
  type: object
  properties:
    previousCursor:
      description: The cursor to access the data before the one returned in the response
      type: string
    nextCursor:
      description: The cursor to access the data after the one returned in the response
      type: string

