name: Check configurator disabled
testcases:
- name: disable_configurator
  steps:
  - type: http
    method: POST
    url: '{{.pfserver_webadmin_url}}/api/v1/configurator/complete'
    ignore_verify_ssl: true
    headers:
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 200
      - result.bodyjson.message ShouldEqual "Configuration completed"
    retry: 3
    delay: 20

- name: check_configurator_disabled
  steps:
  - type: http
    method: GET
    url: '{{.pfserver_webadmin_url}}/api/v1/configurator/config/interfaces'
    ignore_verify_ssl: true
    headers:
      "Content-Type": "application/json"
    assertions:
      - result.statuscode ShouldEqual 401
      - result.bodyjson.message ShouldContainSubstring 'The configurator is turned off'
