=== Packer

To build PacketFence, we use link:http://packer.io[Packer] to create link:https://hub.docker.com/u/inverseinc[Docker images] that are then used in a GitLab pipeline.


=== Anatomy of Packer template

PacketFence rely on link:https://hub.docker.com/u/buildpkg[buildpkg Docker
images] to run GitLab pipeline with
link:https://gitlab.com/Orange-OpenSource/gitlab-buildpkg-tools[gitlab-buildpkg-tools]. Packer
template ([filename]`buildpkg.json`) use these images as base to build
inverseinc Docker images.

==== Custom

To start building PacketFence, we need to install specific things in images
like:
* custom repositories to install RPM or DEB packages
* install upstream softwares necessary to build PacketFence if we can't use repo

We use Ansible to cover these steps. Python is already installed in Docker images.


==== Build dependencies

==== Golang environment

==== Clean up

=== How to build Docker images ?

==== Prerequisites

.Install following softwares:
* http://packer.io/intro/getting-started/install.html[Packer] (>=1.4.2)
* https://docs.docker.com/install/[Docker]
* Ansible

==== Commands
[source,bash]
----
cd ci/packer
make

# only run this builder
packer -only="pfbuild-centos7" buildpkg.json

# ask what to do on error, if you want to look in container
packer build -on-error ask -only="pfbuild-centos-7" buildpkg.json
----
