#!/bin/perl
package main;

use lib qw(
    /usr/local/pf/lib
    /usr/local/pf/lib_perl/lib/perl5
);
use strict;
use File::Find ();
use File::Temp qw/ tempfile tempdir /;

our $PFDIR = '/usr/local/pf';

# Set the variable $File::Find::dont_use_nlink if you're using AFS,
# since AFS cheats.

# for the convenience of &wanted calls, including -eval statements:
use vars qw/*name *dir *prune/;
*name   = *File::Find::name;
*dir    = *File::Find::dir;
*prune  = *File::Find::prune;

our @configuration;

sub main {
    # Traverse desired filesystems
    File::Find::find( { wanted => \&is_configuration }, $PFDIR );
    my ( $fh, $filename ) = tempfile();

    for my $f (@configuration) {
        print $fh "$f\n";
    }

    create_tar( $filename, "out.tar.gz" );
}

sub create_tar {
    my ($file, $out) = @_;
    system("tar", "--files-from=$file", "-zc", "-f", $out );
}

sub populate_config {
    File::Find::find( { wanted => \&is_configuration }, $PFDIR );
}

sub is_configuration {
    my ($dev,$ino,$mode,$nlink,$uid,$gid);
    if ((($dev,$ino,$mode,$nlink,$uid,$gid) = lstat($_)) && -f _ ) {
        if (/^(.*)\.example\z/si) {
            my $file = "$dir/$1";
            if (-e $file) {
                push @configuration, $file
            }
            return;
        }
    }
}

main( @ARGV ) unless caller();

=head1 AUTHOR

Inverse inc. <info@inverse.ca>

=head1 COPYRIGHT

Copyright (C) 2005-2021 Inverse inc.

=head1 LICENSE

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
USA.

=cut

1;

1;
