import { BaseViewResource } from '../../_components/new/'
import {
  BaseFormButtonBar,
  BaseFormGroupInput,
  BaseFormGroupInputNumber,
  BaseFormGroupSwitch,
} from '@/components/new/'
import TheForm from './TheForm'
import TheView from './TheView'

export {
  BaseFormButtonBar                   as FormButtonBar,

  BaseFormGroupSwitch                 as FormGroupApiFrontend,
  BaseFormGroupSwitch                 as FormGroupFingerbankCollector,
  BaseFormGroupSwitch                 as FormGroupGaleraAutofix,
  BaseFormGroupSwitch                 as FormGroupHaproxyAdmin,
  BaseFormGroupSwitch                 as FormGroupHaproxyDb,
  BaseFormGroupSwitch                 as FormGroupHaproxyPortal,
  BaseFormGroupSwitch                 as FormGroupHttpdAaa,
  BaseFormGroupSwitch                 as FormGroupHttpdAdmin,
  BaseFormGroupSwitch                 as FormGroupHttpdAdminDispatcher,
  BaseFormGroupSwitch                 as FormGroupHttpdDispatcher,
  BaseFormGroupSwitch                 as FormGroupHttpdPortal,
  BaseFormGroupSwitch                 as FormGroupHttpdWebservices,
  BaseFormGroupSwitch                 as FormGroupIptables,
  BaseFormGroupSwitch                 as FormGroupIp6tables,
  BaseFormGroupSwitch                 as FormGroupKeepalived,
  BaseFormGroupInput                  as FormGroupNetflowAddress,
  BaseFormGroupSwitch                 as FormGroupNetdata,
  BaseFormGroupSwitch                 as FormGroupPfacct,
  BaseFormGroupSwitch                 as FormGroupPfcron,
  BaseFormGroupSwitch                 as FormGroupPfdhcp,
  BaseFormGroupSwitch                 as FormGroupPfdhcplistener,
  BaseFormGroupInputNumber            as FormGroupPfdhcplistenerPacketSize,
  BaseFormGroupSwitch                 as FormGroupPfdns,
  BaseFormGroupSwitch                 as FormGroupPffilter,
  BaseFormGroupSwitch                 as FormGroupPfipset,
  BaseFormGroupSwitch                 as FormGroupPfperlApi,
  BaseFormGroupSwitch                 as FormGroupPfpki,
  BaseFormGroupSwitch                 as FormGroupPfqueueBackend,
  BaseFormGroupSwitch                 as FormGroupPfqueueGo,
  BaseFormGroupSwitch                 as FormGroupPfsso,
  BaseFormGroupSwitch                 as FormGroupPfstats,
  BaseFormGroupSwitch                 as FormGroupProxysql,
  BaseFormGroupSwitch                 as FormGroupRadiusd,
  BaseFormGroupSwitch                 as FormGroupRadiusdAcct,
  BaseFormGroupSwitch                 as FormGroupRadiusdAuth,
  BaseFormGroupSwitch                 as FormGroupRadsniff,
  BaseFormGroupSwitch                 as FormGroupRedisCache,
  BaseFormGroupSwitch                 as FormGroupRedisNtlmCache,
  BaseFormGroupSwitch                 as FormGroupRedisQueue,
  BaseFormGroupSwitch                 as FormGroupSnmpTrapd,
  BaseFormGroupSwitch                 as FormGroupTrackingConfig,
  BaseFormGroupSwitch                 as FormGroupMysqlProbe,
  BaseFormGroupSwitch                 as FormGroupKafka,
  BaseFormGroupSwitch                 as FormGroupNtlmAuthApi,

  BaseViewResource                    as BaseView,
  TheForm,
  TheView
}
