FROM debian:11

ENV DEBIAN_FRONTEND=noninteractive 

ARG workdir

WORKDIR ${workdir}

RUN apt-get update && \
    apt-get install -yq systemd systemd-sysv gnupg sudo perl vim wget curl ansible iptables-persistent ca-certificates gettext

RUN ln -s /usr/bin/perl /bin/perl &&  ln -s /usr/sbin/iptables-restore  /sbin/iptables-restore && \
    ln -s /usr/sbin/iptables-save /sbin/iptables-save && ln -s /usr/sbin/iptables /sbin/iptables
    
    
RUN echo 'deb http://inverse.ca/downloads/PacketFence/debian/13.0 bullseye bullseye' > \
    /etc/apt/sources.list.d/packetfence.list
RUN wget -q -O - https://inverse.ca/downloads/GPG_PUBLIC_KEY | sudo apt-key add -

#RUN mkdir test && cd test && wget https://github.com/inverse-inc/packetfence/archive/refs/tags/stable.tar.gz && \ 
#    tar -zxvf stable.tar.gz

RUN install -m 0755 -d /etc/apt/keyrings && \ 
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

RUN echo  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update

RUN apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

RUN systemctl enable docker 

EXPOSE 80 1443 443

VOLUME [ "/sys/fs/cgroup" ]


#RUN printf "systemctl start systemd-logind" >> /etc/profile

#CMD ["/sbin/init"]
CMD ["/lib/systemd/systemd"]
#ENTRYPOINT ["/usr/sbin/init", "&"]

