#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=api-frontend

args=`base_args $name`
args="$args --env-file /usr/local/pf/docker/api-frontend/api-frontend_localdev.env -v /usr/local/pf/conf:/usr/local/pf/conf -p 9999:9999"

cd /usr/local/pf/

run $name "$args"
