#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=api-frontend

args=`base_args $name`
args="$args -v /usr/local/pf/var/conf:/usr/local/pf/var/conf -v /usr/local/pf/conf:/usr/local/pf/conf"
args="$args -v /usr/local/pf/logs:/usr/local/pf/logs"
args="$args -p 9999:9999"

run $name "$args"
