#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=kafka

args=`base_args $name`
args+=" -v /usr/local/pf/var/kafka:/usr/local/pf/var/kafka"
args+=" -v /etc/group:/etc/group:ro"
args+=" -v /etc/passwd:/etc/passwd:ro"
args+=" -v /etc/shadow:/etc/shadow:ro"

args+=" -p 9092:9092"
args+=" -p 29092:29092"
args+=" -p 9093:9093"
args+=" --env-file /usr/local/pf/var/conf/$name.env"

run $name "$args"
