#!/usr/bin/perl

=head1 NAME

p0f-wrapper - wrapper around p0f to start the PacketFence p0f processes

=cut

use strict;
use warnings;
use lib qw( /usr/local/pf/lib );
use pf::services::manager::p0f;
use pf::services::util;

my $cmd = pf::services::manager::p0f->new()->_cmdLine();
createpid('p0f');

unless(exec($cmd)) {
    deletepid('p0f');
    exit 127;
}
