#!/usr/bin/perl

use strict;
use warnings;

use lib qw(/usr/local/pf/lib /usr/local/pf/lib_perl/lib/perl5);

use pf::services::util;
use POSIX qw(:signal_h :sys_wait_h setuid setgid setpgid);
use pf::log;
use pf::cluster;
use pf::config qw(
    %Config
);
use pf::util;
use DBI;
use pf::constants;
use JSON::MaybeXS;
use pf::AtFork;
use pf::CHI;
use List::MoreUtils qw(any);

our $PROGRAM_NAME = $0 = "pf-mariadb";

my $logger = get_logger( $PROGRAM_NAME );

our $RUNNING = 1;

our $MYSQLD_SPAWNER_PID;
# Process group of a foreground mysqld_safe run (e.g. --wsrep-recover)
our $MYSQLD_SYNC_PGID;
our $QUORUM_MGMT_SERVER_PID;
our $QUORUM_CLIENT_SERVER_PID;
our $IS_CHILD;

# How many times should we attempt to connect to a galera cluster when an alive quorum is there
# After this, the management node will declare a new cluster if its not in maintenance mode
# TODO: move this to configuration
our $PEERS_ALIVE_CONNECT_ATTEMPT = 1;

# Time to wait between starts after a failure
# TODO: move this to configuration
our $WAIT_TIME_FAIL = 10;

# Time to wait between attempts to discover alive servers
# TODO: move this to configuration
our $WAIT_TIME_ALIVE = 10;

# We start with the assumption that we failed
our $failed = $TRUE;
our $failed_counts = {};

our $MYSQL_CONNECT_TIMEOUT = 5;

# Seconds stop_mysql waits for the mysqld spawner to exit (below the unit's TimeoutSec)
our $STOP_TIMEOUT = 600;

our $GALERA_ENABLED = ($cluster_enabled && isenabled($Config{active_active}{galera_replication}));

our $SLAVE = (defined($ConfigCluster{CLUSTER}{masterslavemode}) ? $TRUE : $FALSE);

# init signal handlers
# %SIG handlers are deferred by perl until it is safe to run them (unlike
# POSIX::sigaction without ->safe(1)), so they can't deadlock in malloc & co.
$SIG{CHLD} = \&child_sighandler;
$SIG{TERM} = \&normal_sighandler;
$SIG{INT}  = \&normal_sighandler;


my $STARTED_BECAUSE;

=head2 record_started_because

Increment a counter for a starting strategy

=cut

sub record_started_because {
    my ($started_because) = @_;
    if(!$started_because) {
        die "Missing starting reason";
    }

    $STARTED_BECAUSE = $started_because;

}

=head2 launch_mysql

Launch MySQL/MariaDB with a specific set of arguments

=cut

sub launch_mysql {
    my ($exec, @args) = @_;
    $exec //= 1;

    @args = grep { defined && length } @args;
    # Must not lookup in /sbin for mysqld, but in /usr/sbin
    $ENV{PATH} = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin:/bin";
    my @cmd = ("mysqld_safe", "--defaults-file=/usr/local/pf/var/conf/mariadb.conf", @args);
    print "Starting MySQL with command: @cmd \n";
    if($exec) {
        exec(@cmd);
    } else {
        run_mysql_sync(@cmd);
    }
}

=head2 run_mysql_sync

Run mysqld_safe in the foreground in its own process group so that
normal_sighandler can interrupt it (mysqld_safe ignores SIGTERM, so the whole
group is signaled to reach mysqld)

=cut

sub run_mysql_sync {
    my (@cmd) = @_;

    # Block SIGTERM/SIGINT across the fork so the handler can't run before
    # $MYSQLD_SYNC_PGID is set, and SIGCHLD so child_sighandler can't reap
    # the child before our waitpid
    my $sigset = POSIX::SigSet->new(SIGTERM, SIGINT, SIGCHLD);
    my $old_sigset = POSIX::SigSet->new;
    sigprocmask(SIG_BLOCK, $sigset, $old_sigset)
        or die("pf-mariadb could not block signals: $!");

    if(!$RUNNING) {
        sigprocmask(SIG_SETMASK, $old_sigset);
        return;
    }

    my $pid = pf::AtFork::pf_fork();

    if(!defined($pid)) {
        sigprocmask(SIG_SETMASK, $old_sigset);
        $logger->error("pf-mariadb could not fork: $!");
        return;
    }

    if($pid == 0) {
        $SIG{CHLD} = "DEFAULT";
        $SIG{TERM} = "DEFAULT";
        $SIG{INT}  = "DEFAULT";
        $IS_CHILD = 1;
        setpgid(0, 0);
        sigprocmask(SIG_SETMASK, $old_sigset);
        exec(@cmd) or POSIX::_exit(127);
    }

    # Also set it from the parent to avoid racing the child's setpgid
    setpgid($pid, $pid);
    $MYSQLD_SYNC_PGID = $pid;

    # Let SIGTERM/SIGINT through while waiting, keep SIGCHLD blocked
    my $unblock_sigset = POSIX::SigSet->new(grep { !$old_sigset->ismember($_) } SIGTERM, SIGINT);
    sigprocmask(SIG_UNBLOCK, $unblock_sigset);

    waitpid($pid, 0);
    $MYSQLD_SYNC_PGID = undef;
    sigprocmask(SIG_SETMASK, $old_sigset);
}

=head2 fork_launch_mysql

Fork and start MySQL/MariaDB
Also record the startup method for future usage

=cut

sub fork_launch_mysql {
    my ($started_because, @args) = @_;

    # Block SIGTERM/SIGINT across the fork so the handler can't run before
    # $MYSQLD_SPAWNER_PID is set (parent) or before the handlers are reset (child)
    my $sigset = POSIX::SigSet->new(SIGTERM, SIGINT);
    my $old_sigset = POSIX::SigSet->new;
    sigprocmask(SIG_BLOCK, $sigset, $old_sigset)
        or die("pf-mariadb could not block signals: $!");

    if(!$RUNNING) {
        sigprocmask(SIG_SETMASK, $old_sigset);
        return;
    }

    record_started_because($started_because);

    my $pid = pf::AtFork::pf_fork();

    if(!defined($pid)) {
        sigprocmask(SIG_SETMASK, $old_sigset);
        $logger->error("pf-mariadb could not fork: $!");
    } elsif($pid) {
        $MYSQLD_SPAWNER_PID = $pid;
        sigprocmask(SIG_SETMASK, $old_sigset);
    } else {
        $SIG{CHLD} = "DEFAULT";
        $SIG{TERM} = "DEFAULT";
        $SIG{INT}  = "DEFAULT";
        $IS_CHILD = 1;
        # The signal mask is inherited across exec
        sigprocmask(SIG_SETMASK, $old_sigset);

        my (undef, undef,$uid,$gid) = getpwnam('mysql');
        my $sockdir = "/var/run/mysqld";
        mkdir $sockdir;
        chown $uid, $gid, $sockdir;
        setgid($gid);
        setuid($uid);

        $0 = "pf-mariadb - mysqld spawner";
        launch_mysql($TRUE, @args);
        $RUNNING = 0;
        exit;
    }
}

=head2 ping_quorum

Whether or not there is a ping quorum (i.e. servers are booted and online)

=cut

sub ping_quorum {
    my $alive = 0;
    foreach my $server (pf::cluster::mysql_servers()) {
        if(ping($server->{management_ip})) {
            $alive ++;
        }
    }
    return ($alive > (scalar(pf::cluster::db_enabled_hosts()) / 2));
}

=head2 test_db

Test the connection to the database for a specific host using the replication credentials

=cut

sub test_db {
    my ($host) = @_;
    my $mydbh = DBI->connect( "dbi:mysql:dbname=mysql;host=$host;port=3306;mysql_connect_timeout=$MYSQL_CONNECT_TIMEOUT",
        $Config{active_active}{galera_replication_username}, $Config{active_active}{galera_replication_password}, { RaiseError => 0, PrintError => 0, mysql_auto_reconnect => 1 } );
    # make sure we have a database handle
    if ($mydbh) {
        return 1;
    }
    else {
        return 0;
    }
}

=head2 db_available

One of the cluster members has its database running.

=cut

sub db_available {
    my $alive = 0;

    foreach my $server (pf::cluster::mysql_servers()) {
        my $host = $server->{management_ip};
        $alive ++ if(test_db($host));
    }
    return ($alive > 0);
}

=head2 get_failed_count

Get the count of fails for a specific startup method

=cut

sub get_failed_count {
    return $failed_counts->{$_[0]} // 0;
}

=head2 startup_clean_shutdown

Startup procedure when service was cleanly shutdown

=cut

sub startup_clean_shutdown {
    my $safe_to_bootstrap = `cat /var/lib/mysql/grastate.dat | grep 'safe_to_bootstrap: 1'`;
    if(db_available()) {
        $logger->info("There is a peer with an alive DB. Will attempt to connect to the cluster");
        fork_launch_mysql("db-peer-available");
    }
    elsif($safe_to_bootstrap || ping_quorum()) {
        if($safe_to_bootstrap) {
            $logger->info("This node is safe to bootstrap from. Starting in bootstrap mode.");
            bootstrap_new_cluster();
        }
        else {
            $logger->info("This node is not safe to bootstrap from. Starting in normal mode to connect to a bootstrapped peer.");
            fork_launch_mysql("peers-alive-no-db-attempt-connect-to-bootstrapped");
        }
    }
    else {
        $logger->info("There isn't a ping quorum yet nor a server with an alive database, will wait until the majority of the servers are alive.");
        sleep $WAIT_TIME_ALIVE;
        attempt_start();
    }
}


=head2 _check_pid

Check if a PID is alive

=cut

sub _check_pid {
    my ($pid) = @_;
    return $pid && kill(0, $pid);
}

=head2 attempt_start

Attempt a startup of MySQL based on the current state of things

Refer to the clustering guide for details on how this works.

=cut

sub attempt_start {
    return if !$RUNNING;
    clean_wsrep_recovery();
    launch_mysql($FALSE, "--wsrep-recover") if !$SLAVE;
    # Just start it without anything special if we're in standalone mode or if we're a single cluster node
    if(!$GALERA_ENABLED || scalar(pf::cluster::db_enabled_hosts()) == 1) {
        fork_launch_mysql("standalone");
    }
    elsif ($SLAVE) {
        launch_mysql($FALSE, "");
        fork_launch_mysql("standalone");
    }
    elsif(!_check_pid($MYSQLD_SPAWNER_PID) && -f "/var/lib/mysql/gvwstate.dat") {
        fork_launch_mysql("dirty-shutdown");
    }
    else {
        startup_clean_shutdown();
    }
}

=head2 clean_wsrep_recovery

Will clean wsrep_recovery.* files in the MySQL data dir

=cut

sub clean_wsrep_recovery {
    File::Find::find({wanted => sub {
        my ($dev,$ino,$mode,$nlink,$uid,$gid);

        (($dev,$ino,$mode,$nlink,$uid,$gid) = lstat($_)) &&
        -f _ &&
        /^wsrep_recovery\..*\z/s &&
        unlink($_);
    }}, '/var/lib/mysql/');
}

=head2 bootstrap_new_cluster

=cut

sub bootstrap_new_cluster {
    `sed -i.bak "s/safe_to_bootstrap: 0/safe_to_bootstrap: 1/g" /var/lib/mysql/grastate.dat`;
    `rm -f /var/lib/mysql/gvwstate.dat`;
    launch_mysql($FALSE, "--wsrep-recover");
    fork_launch_mysql("create-new-cluster", "--wsrep-new-cluster");
}

if(pf::cluster::is_in_maintenance) {
    my $msg = "Not starting because this node is in maintenance mode";
    print STDERR "$msg\n";
    $logger->error($msg);
    exit;
}

if(defined($ARGV[0]) && $ARGV[0] eq "--force-new-cluster") {
    bootstrap_new_cluster();
    # Block SIGTERM/SIGINT so a signal arriving between the $RUNNING check and
    # the wait isn't lost (which would hang in pause until SIGKILL)
    my $old_sigset = POSIX::SigSet->new;
    sigprocmask(SIG_BLOCK, POSIX::SigSet->new(SIGTERM, SIGINT), $old_sigset)
        or die("pf-mariadb could not block signals: $!");
    while($RUNNING) {
        sigsuspend($old_sigset);
    }
    sigprocmask(SIG_SETMASK, $old_sigset);
    stop_mysql();
    exit;
}

# Do an initial startup
attempt_start();

while($RUNNING){
    if(!_check_pid($MYSQLD_SPAWNER_PID)) {
        $failed = $TRUE;
        print "Failed starting with mode: $STARTED_BECAUSE \n";
        $failed_counts->{$STARTED_BECAUSE} //= 0;
        $failed_counts->{$STARTED_BECAUSE} ++;

        print "MariaDB is not alive \n";
        attempt_start();
    }
    elsif($GALERA_ENABLED) {
        if(test_db(pf::cluster::current_server()->{management_ip})) {
            # We're coming from a previous failure, so we log it 
            if($failed) {
                $logger->info("Successful clustered connection to the DB.");
            }
            $failed_counts = {};
            $failed = $FALSE;
        }
        else {
            $failed = $TRUE;
        }
    }
    sleep 5;
}

stop_mysql();

END {
    deletepid();
}

exit(0);

=head2 normal_sighandler

Cleanup and stop processing when geting a signal

=cut

sub normal_sighandler {
    $RUNNING = 0;
    if(!$IS_CHILD) {
        # Don't listen to child signals anymore when cleaning up
        $SIG{CHLD} = "IGNORE";

        kill(SIGTERM, $MYSQLD_SPAWNER_PID) if($MYSQLD_SPAWNER_PID);
        kill(-SIGTERM(), $MYSQLD_SYNC_PGID) if($MYSQLD_SYNC_PGID);
        kill(SIGTERM, $QUORUM_MGMT_SERVER_PID) if($QUORUM_MGMT_SERVER_PID);
        kill(SIGTERM, $QUORUM_CLIENT_SERVER_PID) if($QUORUM_CLIENT_SERVER_PID);
        # no fork in a signal handler (deadlocks): stop_mysql runs pkill
        deletepid();
    }
}

=head2 stop_mysql

Kill leftover mysqld processes once the main loop has stopped

=cut

sub stop_mysql {
    my $deadline = time + $STOP_TIMEOUT;
    while(1) {
        # Repeat the pkill: mysqld_safe ignores SIGTERM and may start mysqld
        # after a previous pkill found nothing to kill
        system('pkill', 'mysqld');
        system('pkill', 'mariadbd');
        # mysqld_safe exits once mysqld is down, wait for it so we don't exit
        # while the database is still shutting down
        last if !$MYSQLD_SPAWNER_PID || waitpid($MYSQLD_SPAWNER_PID, WNOHANG) != 0;
        if(time >= $deadline) {
            $logger->warn("mysqld spawner $MYSQLD_SPAWNER_PID still running after ${STOP_TIMEOUT}s, giving up waiting");
            last;
        }
        sleep 1;
    }
    $logger->debug("pfmariadb terminating");
}

=head2 child_sighandler

When a child dies, we cleanup any leftover mysqld processes

=cut

sub child_sighandler {
    local ($!, $?);

    while(1) {
        my $child = waitpid(-1, WNOHANG);
        last unless $child > 0;
    }
}
