#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfacct

set -a
. /usr/local/pf/var/conf/acct.env
set +a

args=`base_args $name`
args="$args -v /usr/local/pf/conf/system_init_key:/usr/local/pf/conf/system_init_key"
args="$args -v /usr/local/pf/raddb:/usr/local/pf/raddb"
args="$args -v /usr/share/freeradius:/usr/share/freeradius"
args="$args -p 2056:2056/udp"
args="$args $PFACCT_ADDRESS"

run $name "$args"
