#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfconnector-server

args=`base_args $name`
args="$args --network=host"

run $name "$args" "/usr/local/pf/sbin/pfconnector server --host 127.0.0.1 --port 22226 --reverse"
