#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=pfconfig

args=`base_args $name`
args="$args -v/usr/local/pf/conf:/usr/local/pf/conf -p 44444:44444 -e PF_MYSQL_UNIX_SOCKET=''"

run $name "$args"
