#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfconnector-client

args=`base_args $name`
args="$args --network=host"

unified_api_system_pass=`cat /usr/local/pf/conf/unified_api_system_pass`
run $name "$args" "/usr/local/pf/sbin/pfconnector client --auth=local_connector:$unified_api_system_pass --tls-skip-verify https://127.0.0.1:9999/api/v1/pfconnector/tunnel"
