#!/bin/bash

args="--sig-proxy=true -v/usr/local/pf/conf:/usr/local/pf/conf -v /usr/local/pf/var/run/:/usr/local/pf/var/run/  -p 44444:44444 --rm -ti --name=pfconfig"

mysql_sock=""

if [ -e /etc/debian_version ]; then
  mysql_sock="/var/run/mysqld/mysqld.sock"
else
  mysql_sock="/var/lib/mysql/mysql.sock"
fi


if [ -e $mysql_sock ]; then
  args="$args -v $mysql_sock:/run/mysqld/mysqld.sock"
fi

cd /usr/local/pf/
rm -f var/run/pfconfig.sock var/run/pfconfig.pid
docker container rm -f pfconfig

docker run $args --name=pfconfig $(docker build -q -f docker/pfconfig/Dockerfile .)
