#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfcron

args=`base_args $name`
args="$args -v /usr/local/pf/raddb/certs:/usr/local/pf/raddb/certs -v /usr/local/pf/conf/ssl:/usr/local/pf/conf/ssl"

run $name "$args"
