#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfdns-connector

args=`base_args $name`
args="$args -v /usr/local/pf/conf:/usr/local/pf/conf -v /usr/local/pf/var/conf:/usr/local/pf/var/conf -p 5353:53/udp -p 5353:53/tcp"

run $name "$args"
