#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfldapexplorer

args=`base_args $name`
args="$args -v /usr/local/pf/conf:/usr/local/pf/conf -p 100.64.0.1:22229:22229 -p 127.0.0.1:22229:22229"

cd /usr/local/pf/

run $name "$args"