#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=pfperl-api

args=`base_args $name`
args="$args --env-file /usr/local/pf/docker/pfperl-api/localdev.env -v /usr/local/pf/conf:/usr/local/pf/conf -p 22224:22224"

cd /usr/local/pf/

run $name "$args"
