#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfperl-api

args=`base_args $name`
args="$args -v /usr/local/pf/var:/usr/local/pf/var -v /usr/local/pf/conf:/usr/local/pf/conf -v /usr/local/pf/raddb/certs:/usr/local/pf/raddb/certs"
args="$args -v /usr/local/pf/html/captive-portal/profile-templates:/usr/local/pf/html/captive-portal/profile-templates"
args="$args --privileged -v /run/systemd/system:/run/systemd/system -v /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
args="$args -v /usr/local/fingerbank/conf:/usr/local/fingerbank/conf"
args="$args -v/usr/local/pf/pfk8s-conf:/usr/local/pf/pfk8s-conf"
args="$args --network=host"

run $name "$args"
