#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfpki

args=`base_args $name`
args="$args -v /usr/local/pf/conf:/usr/local/pf/conf -p 22225:22225"
args="$args -p 2024:2024"
args="$args -v /usr/local/pf/html/captive-portal/templates:/usr/local/pf/html/captive-portal/templates"

run $name "$args"
