#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfqueue

args=`base_args $name`
args="$args -v/usr/local/pf/conf/:/usr/local/pf/conf/ --network=host"
args="$args -v/usr/local/pf/html/captive-portal/profile-templates:/usr/local/pf/html/captive-portal/profile-templates"

run $name "$args"
