#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=pfsso

args=`base_args $name`
args="$args -v /usr/local/pf/conf:/usr/local/pf/conf -p 8777:8777"

cd /usr/local/pf/

run $name "$args"
