#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=pfsso

args=`base_args $name`
args="$args --env-file /usr/local/pf/docker/pfsso/localdev.env -v /usr/local/pf/conf:/usr/local/pf/conf -p 8777:8777"

cd /usr/local/pf/

run $name "$args"
