#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=radius-acct

args=`base_args $name`
args="$args --env-file /usr/local/pf/docker/$name/localdev.env --mount type=bind,source=/usr/local/pf/conf/log.conf.d/,target=/usr/local/pf/conf/log.conf.d/ --mount type=bind,source=/usr/local/pf/raddb/,target=/usr/local/pf/raddb/ --mount type=bind,source=/usr/local/pf/lib/,target=/usr/local/pf/lib/ -v /var/lib/mysql/mysql.sock:/run/mysqld/mysqld.sock --mount type=bind,source=/usr/local/pf/bin/,target=/usr/local/pf/bin/ --device /dev/fuse --cap-add=SYS_ADMIN --security-opt apparmor:unconfined -p 100.64.0.1:1813:1813"

run $name "$args"
