#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=radius-acct

args=`base_args $name`
args="$args --mount type=bind,source=/usr/local/pf/conf/log.conf.d/,target=/usr/local/pf/conf/log.conf.d/ --mount type=bind,source=/usr/local/pf/conf/ssl/,target=/usr/local/pf/conf/ssl/ --mount type=bind,source=/usr/local/pf/raddb/,target=/usr/local/pf/raddb/ -v /var/lib/mysql/mysql.sock:/run/mysqld/mysqld.sock -p 1813:1813/udp"

run $name "$args"
