#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=radius-cli

args=`base_args $name`
args="$args --mount type=bind,source=/usr/local/pf/raddb/,target=/usr/local/pf/raddb/"

run $name "$args"
