#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=radiusd-auth

args=`base_args $name`
args="$args -v /usr/local/pf/conf/log.conf.d/:/usr/local/pf/conf/log.conf.d/ -v /usr/local/pf/conf/ssl/:/usr/local/pf/conf/ssl/ -v /usr/local/pf/raddb/:/usr/local/pf/raddb/ -v /var/lib/mysql/mysql.sock:/run/mysqld/mysqld.sock -p 1812:1812/udp"

run $name "$args"
