#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=radius-auth

args=`base_args $name`
args="$args --mount type=bind,source=/usr/local/pf/raddb/,target=/usr/local/pf/raddb/ -mount type=bind,source=/usr/local/pf/conf/certmanager/,target=/usr/local/pf/conf/certmanager/"

run $name "$args"
