#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=radiusd-eduroam

args=`base_args $name`
args="$args -v /usr/local/pf/conf/log.conf.d/:/usr/local/pf/conf/log.conf.d/ -v /usr/local/pf/conf/ssl/:/usr/local/pf/conf/ssl/ -v /usr/local/pf/raddb/:/usr/local/pf/raddb/ -v /var/lib/mysql/mysql.sock:/run/mysqld/mysqld.sock -p 11812:11812/udp"

run $name "$args"
