#!/bin/bash

source /usr/local/pf/containers/systemd-service

name=radiusd-load-balancer

set -a
. /usr/local/pf/var/conf/$name.env
set +a

args=`base_args $name`
args="$args -v /usr/local/pf/conf/log.conf.d/:/usr/local/pf/conf/log.conf.d/"
args="$args -v /usr/local/pf/conf/ssl/:/usr/local/pf/conf/ssl/"
args="$args -v /usr/local/pf/raddb/:/usr/local/pf/raddb/"
args="$args -v /var/lib/mysql/mysql.sock:/run/mysqld/mysqld.sock"
args="$args -p 100.64.0.1:1812:1812/udp"

run $name "$args"
