#!/bin/bash

source /usr/local/pf/docker/systemd-service

name=radius-auth

args=`base_args $name`
args="$args --env-file /usr/local/pf/docker/$name/localdev.env --mount type=bind,source=/usr/local/pf/raddb/,target=/usr/local/pf/raddb/ --mount type=bind,source=/usr/local/pf/conf/,target=/usr/local/pf/conf/ --mount type=bind,source=/usr/local/pf/lib/,target=/usr/local/pf/lib/ -v /var/lib/mysql/mysql.sock:/run/mysqld/mysqld.sock --mount type=bind,source=/usr/local/pf/bin/,target=/usr/local/pf/bin/ -p 100.64.0.1:1812:1812"

run $name "$args"
