#!/bin/sh
# postinst script for packetfence-ntlm-auth-api
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Force the LC_CTYPE to C to avoid i18n problems during postinstallation.
LC_CTYPE=C
export LC_CTYPE

case "$1" in
    configure)
    # get containers image and tag them locally
    /usr/local/ntlm-auth-api/containers/manage-images.sh
    /bin/systemctl daemon-reload
    #/bin/systemctl enable packetfence-ntlm-auth-api-remote.service
    if [ -n "$2" ]; then
        if systemctl is-active --quiet "packetfence-ntlm-auth-api-remote.service"; then
            echo "Upgrade detected, restarting packetfence-ntlm-auth-api-remote service"
            /bin/systemctl restart packetfence-ntlm-auth-api-remote.service
        fi
    else
        /bin/systemctl stop packetfence-ntlm-auth-api-remote.service
    fi
    
    echo "NTLM Auth API installation completed"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
