Document: packetfence
Title: Debian packetfence Manual
Author: <insert document author here>
Abstract: This manual describes what packetfence is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/packetfence/packetfence.sgml.gz

Format: postscript
Files: /usr/share/doc/packetfence/packetfence.ps.gz

Format: text
Files: /usr/share/doc/packetfence/packetfence.text.gz

Format: HTML
Index: /usr/share/doc/packetfence/html/index.html
Files: /usr/share/doc/packetfence/html/*.html
