#!/bin/sh
# prerm script for packetfence-ntlm-auth-join-remote
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove|deconfigure)
        /bin/systemctl stop packetfence-ntlm-auth-join-remote.service 2>/dev/null || true
        /bin/systemctl disable packetfence-ntlm-auth-join-remote.service 2>/dev/null || true
        /bin/systemctl reset-failed packetfence-ntlm-auth-join-remote.service 2>/dev/null || true
    ;;
    upgrade|failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
