#!/bin/sh
# postinst script for packetfence-pfconnector
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Force the LC_CTYPE to C to avoid i18n problems during postinstallation.
LC_CTYPE=C
export LC_CTYPE

case "$1" in
    configure)
    if ! grep -q "containers-gateway.internal" /etc/hosts; then
        echo "127.0.0.1 containers-gateway.internal" >> /etc/hosts
    fi
    if [ ! -f /usr/local/pfconnector-remote/raddb/certs/server.pem ]; then
        make -C /usr/local/pfconnector-remote/raddb/certs
    fi
    cp /usr/local/pfconnector-remote/raddb/sites-available/status /usr/local/pfconnector-remote/raddb/sites-enabled/status
    /usr/local/pfconnector-remote/upgrade/remove-unpackaged-pfconnector.sh
    # get containers image and tag them locally
    /usr/local/pfconnector-remote/containers/manage-images.sh
    /bin/systemctl daemon-reload
    /bin/systemctl enable packetfence-pfconnector-remote-combined.service
    if [ -n "$2" ]; then
        if systemctl is-active --quiet "packetfence-pfconnector-remote-combined.service"; then
            echo "Upgrade detected, restarting packetfence-pfconnector-remote-combined service"
            /bin/systemctl restart packetfence-pfconnector-remote-combined.service
        fi
    else
        /bin/systemctl stop packetfence-pfconnector-remote-combined.service
    fi

    if ! grep 'containers-gateway.internal' /etc/hosts > /dev/null; then
        echo "" >> /etc/hosts
        echo "100.64.0.1 containers-gateway.internal" >> /etc/hosts
    fi
    
    echo ""
    echo "Connector installation completed"
    echo ""
    echo "Run /usr/local/pfconnector-remote/bin/pfconnector-configure to setup the pfconnector-remote"
    echo ""
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
