import {BaseViewCollectionItem} from '../../_components/new/'
import {
  BaseFormButtonBar,
  BaseFormGroupChosenMultiple,
  BaseFormGroupChosenOne,
  BaseFormGroupFileUpload,
  BaseFormGroupInput,
  BaseFormGroupInputNumber,
  BaseFormGroupInputPassword,
  BaseFormGroupSwitch,
  BaseFormGroupTextareaUpload,
} from '@/components/new/'
import {BaseFormGroupOses} from '@/views/Configuration/_components/new/'
import TheForm from './TheForm'
import TheView from './TheView'

export {
  BaseViewCollectionItem                    as BaseView,
  BaseFormButtonBar                         as FormButtonBar,

  BaseFormGroupInput                        as FormGroupAndroidAgentDownloadUri,
  BaseFormGroupInput                        as FormGroupAndroidDownloadUri,
  BaseFormGroupInputPassword                as FormGroupApiPassword,
  BaseFormGroupInputPassword                as FormGroupApiToken,
  BaseFormGroupInput                        as FormGroupApiUsername,
  BaseFormGroupInput                        as FormGroupApplicationIdentifier,
  BaseFormGroupInputPassword                as FormGroupApplicationSecret,
  BaseFormGroupSwitch                       as FormGroupApplyRole,
  BaseFormGroupSwitch                       as FormGroupAutoRegister,
  BaseFormGroupInput                        as FormGroupBoardingHost,
  BaseFormGroupInputNumber                  as FormGroupBoardingPort,
  BaseFormGroupSwitch                       as FormGroupBroadcast,
  BaseFormGroupFileUpload                   as FormGroupCaCertPath,
  BaseFormGroupSwitch                       as FormGroupCanSignProfile,
  BaseFormGroupChosenMultiple               as FormGroupCategory,
  BaseFormGroupTextareaUpload               as FormGroupCertChain,
  BaseFormGroupTextareaUpload               as FormGroupCertificate,
  BaseFormGroupInputPassword                as FormGroupClientSecret,
  BaseFormGroupInput                        as FormGroupCustomerId,
  BaseFormGroupInput                        as FormGroupDescription,
  BaseFormGroupSwitch                       as FormGroupDeviceTypeDetection,
  BaseFormGroupInput                        as FormGroupDomains,
  BaseFormGroupSwitch                       as FormGroupDpsk,
  BaseFormGroupSwitch                       as FormGroupDpskUseLocalPassword,
  BaseFormGroupChosenOne                    as FormGroupEapType,
  BaseFormGroupSwitch                       as FormGroupEnforce,
  BaseFormGroupInput                        as FormGroupEnrollUrl,
  BaseFormGroupInputNumber                  as FormGroupExpiresIn,
  BaseFormGroupInputNumber                  as FormGroupExpiresJitter,
  BaseFormGroupInput                        as FormGroupHost,
  BaseFormGroupInput                        as FormGroupIdentifier,
  BaseFormGroupInput                        as FormGroupIosAgentDownloadUri,
  BaseFormGroupInput                        as FormGroupIosDownloadUri,
  BaseFormGroupInput                        as FormGroupLoginUrl,
  BaseFormGroupInput                        as FormGroupMacOsxAgentDownloadUri,
  BaseFormGroupChosenOne                    as FormGroupNonComplianceSecurityEvent,
  BaseFormGroupOses                         as FormGroupOses,
  BaseFormGroupInputPassword                as FormGroupPasscode,
  BaseFormGroupInputPassword                as FormGroupPassword,
  BaseFormGroupChosenOne                    as FormGroupPkiProvider,
  BaseFormGroupInputNumber                  as FormGroupPort,
  BaseFormGroupTextareaUpload               as FormGroupPrivateKey,
  BaseFormGroupChosenOne                    as FormGroupProtocol,
  BaseFormGroupInputNumber                  as FormGroupPskSize,
  BaseFormGroupSwitch                       as FormGroupQueryComputers,
  BaseFormGroupSwitch                       as FormGroupQueryMobileDevices,
  BaseFormGroupChosenMultiple               as FormGroupRules,
  BaseFormGroupChosenOne                    as FormGroupRoleToApply,
  BaseFormGroupChosenOne                    as FormGroupSecurityType,
  BaseFormGroupFileUpload                   as FormGroupServerCertificatePath,
  BaseFormGroupTextareaUpload               as FormGroupServiceAccount,
  BaseFormGroupInput                        as FormGroupSsid,
  BaseFormGroupSwitch                       as FormGroupSyncPid,
  BaseFormGroupInput                        as FormGroupTenantCode,
  BaseFormGroupInput                        as FormGroupTenantIdentifier,
  BaseFormGroupInput                        as FormGroupUsername,
  BaseFormGroupInput                        as FormGroupUser,
  BaseFormGroupInput                        as FormGroupWindowsAgentDownloadUri,
  BaseFormGroupInput                        as FormGroupWindowsPhoneDownloadUri,

  TheForm,
  TheView
}
