#!/bin/bash
grep -v "^#" process_names_to_immunize |while read name; do PIDS_TO_IMMUNIZE=$(pidof $name); for PID_TO_IMMUNIZE in $PIDS_TO_IMMUNIZE; do if [ -e /proc/$PID_TO_IMMUNIZE/oom_adj ]; then echo -17 > /proc/$PID_TO_IMMUNIZE/oom_adj; fi; done; done
