#!/bin/bash

source /usr/local/ntlm-auth-api/containers/systemd-service

name=ntlm-auth-api

conf_dir="/usr/local/ntlm-auth-api/var/conf/"

env_file="$1.env"
IDENTIFIER=$1

if [ -z "$IDENTIFIER" ]; then
    echo "Domain identifier not provided."
    exit 1
fi

if [ ! -f "$conf_dir$env_file" ]; then
    echo "Env file '$conf_dir$env_file' for domain '$IDENTIFIER' not found."
    exit 1
fi

source "$conf_dir$env_file"

echo "Starting ntlm auth api for domain: $1"

args=$(base_args "${name}-${IDENTIFIER}")
args="$args -v /usr/local/ntlm-auth-api/conf:/usr/local/pf/conf"
args="$args -v /usr/local/ntlm-auth-api/logs:/usr/local/pf/logs"
args="$args -v /usr/local/ntlm-auth-api/var/conf:/usr/local/pf/var/conf"
args="$args -v /usr/local/ntlm-auth-api/sbin:/usr/local/pf/sbin"
args="$args -v /var/log:/var/log:ro"
args="$args -p $LISTEN:$LISTEN"
args="$args -e LISTEN=$LISTEN"
args="$args -e IDENTIFIER=$IDENTIFIER"

run_multi "$name" "$IDENTIFIER" "$args"
echo "Done with ntlm auth api for domain $1"
