// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

//== Automation of upgrades

This section covers base automation of upgrades on the same operating system available.

Please, check if there is a "Specific Automation Upgrade" defined between the current version to the chosen version, it may contain specific steps like changing the OS, updating database version, etc.

=== Assumptions and limitations

* Automation may contain **pre-upgrade steps** defined in the following document.
* Perform automated upgrades on **standalone** servers only. Cluster
  upgrades must use the procedure described in the
  <<PacketFence_Clustering_Guide.asciidoc#_performing_an_upgrade_on_a_cluster,Clustering
  Guide>>
* Check "Specific Automation Upgrade" (or "Specific Upgrade") in Upgrading to the needed PacketFence version.
* An exportable backup of the configuration is performed before upgrading

=== Full upgrade

Run following script to perform a full upgrade:

[source,bash]
----
/usr/local/pf/addons/upgrade/do-upgrade.sh
----

