// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

//== Automation of upgrades

Basic upgrade automation on same operating system available since PacketFence 11.0.0.

PacketFence 14.0.0 changes OS from Debian 11 to Debian 12.
For PacketFence 14.0 on Debian 12, create new Debian 12 VM then use <<PacketFence_Installation_Guide.html#_exportimport_mechanism,import/export>> from previous installation.

=== Assumptions and limitations

* Automation may contain **pre-upgrade steps** defined in this document.
* Perform automated upgrades on **standalone** servers only. Cluster upgrades use the <<PacketFence_Clustering_Guide.asciidoc#_performing_an_upgrade_on_a_cluster,Clustering Guide>> procedure.
* Automated upgrades supported:
** PacketFence 11.0.0 to 13.2.0 on Debian 11
** PacketFence 14.0.0+ on Debian 12
** PacketFence 11.0.0+ on RedHat 8
* Exportable configuration backup performed before upgrading

=== Full upgrade (for PacketFence version 11.0.0 only - see next section for 11.1.0 and above)

==== Preliminary steps

On PacketFence version 11.0.0, install the `packetfence-upgrade` package using following instructions:

.RHEL / CentOS based systems **only**
[source,bash]
----
yum install packetfence-upgrade --enablerepo=packetfence
----

.Debian systems **only**
[source,bash]
----
apt update
apt install packetfence-upgrade
----

Then perform a full upgrade using following command:

[source,bash]
----
/usr/local/pf/addons/full-upgrade/run-upgrade.sh
----

=== Full upgrade (for PacketFence versions 11.1.0 and later)

Run following script to perform a full upgrade:

[source,bash]
----
/usr/local/pf/addons/upgrade/do-upgrade.sh
----

