#!/usr/bin/perl

use strict;
use warnings;
BEGIN {
	use lib qw(/usr/local/pf/lib /usr/local/pf/lib_perl/lib/perl5);
	use lib '/usr/local/pf/t';
}

use test_paths_serial;

if (test_paths::testIfFileUnlock($test_paths::PFCONFIG_TEST_PID_FILE)) {
    exec("perl -I/usr/local/pf/lib_perl/lib/perl5 -I/usr/local/pf/t -Mtest_paths_serial /usr/local/pf/sbin/pfconfig -n pfconfig-test-serial -s $pfconfig::constants::SOCKET_PATH -p $test_paths::PFCONFIG_TEST_PID_FILE -c $pfconfig::constants::CONFIG_FILE_PATH -d");
}
