#!/usr/bin/perl

use strict;
use warnings;
BEGIN {
	use lib '/usr/local/pf/t';
}
use test_paths;

if (test_paths::testIfFileUnlock($test_paths::PFCONFIG_TEST_PID_FILE))  {
    exec("perl -I/usr/local/pf/t -Mtest_paths /usr/local/pf/sbin/pfconfig -n pfconfig-test -s $pfconfig::constants::SOCKET_PATH -p $test_paths::PFCONFIG_TEST_PID_FILE -c $pfconfig::constants::CONFIG_FILE_PATH -d");
}

