---
- hosts: pfservers
  name: configure Packetfence VM
  become: True

  vars:
    nodejs_version: "12.x"
    npm_config_unsafe_perm: "true"
    debianPackages:
      - curl
      - python3-pip
      - virtualenv
      - jq

    el8Packages:
      - curl
      - python3-pip
      - python3-setuptools
      - virtualenv
      - jq

  roles:
    # nodejs is already installed on Debian during build of Vagrant images
    - role: geerlingguy.nodejs
      tags: nodejs

  tasks:
    - name: Install packages on debian
      package:
        name: "{{ debianPackages }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install packages on el8
      package:
        name: "{{ el8Packages }}"
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install xmltodict python package
      pip:
        name: xmltodict
