// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Network_Devices_Configuration_Guide.asciidoc
    for authors, copyright and license information.

////


//=== Cisco Small Business (SMB)

Cisco Small Business switches support MAC authentication (MAB), 802.1X, and
VoIP. Both technologies can be combined on the same switchport.

VoIP activation requires no switch configuration; configure voice VLAN in
PacketFence switch configuration and enable VoIP there. Phones must send
untagged traffic when connected to PacketFence-enabled ports. Do not enable
voice VLAN capabilities on switch as they may conflict with PacketFence
authorization attributes.

==== Global configuration

CAUTION: Configure local account or RADIUS server for management before
executing these steps to maintain switch login access.

Define RADIUS server pointing to PacketFence:

  dot1x system-auth-control 
  radius-server key useStrongerSecret
  radius-server host 192.168.1.5

  aaa accounting dot1x start-stop group radius

  snmp-server community public ro view Default 
  snmp-server community private rw view Default 

SNMP configuration for the Cisco SG300:

  snmp-server community public ro view DefaultSuper
  snmp-server community private rw view DefaultSuper

==== MAC Authentication

Configure MAC authentication on each interface:

  interface x/y/z
   dot1x host-mode multi-sessions 
   dot1x reauthentication
   dot1x timeout reauth-period 10800
   dot1x timeout quiet-period 10 
   dot1x timeout server-timeout 5 
   dot1x timeout supp-timeout 3 
   dot1x authentication mac 
   dot1x radius-attributes vlan 
   dot1x port-control auto 
   spanning-tree portfast 
   switchport mode general 
   switchport general pvid 2 

==== 802.1X with MAB

Configure 802.1X with MAC authentication fallback on each interface:

  interface x/y/z
   dot1x host-mode multi-sessions 
   dot1x reauthentication 
   dot1x timeout quiet-period 10 
   dot1x timeout server-timeout 5 
   dot1x timeout supp-timeout 3 
   dot1x authentication dot1x mac 
   dot1x radius-attributes vlan 
   dot1x port-control auto 
   spanning-tree portfast 
   switchport mode general 
   switchport general pvid 2 

Configure switch in PacketFence with following information:

[options="compact"]
* *Definition -> Type*: `Cisco SG500`
* *Definition -> Mode*: `production`
* *Definition -> Deauthentication Method*: `SNMP`
* *Definition -> VoIP* enabled if you need VoIP on this switch.
* *Roles -> voice VLAN* set to the VLAN you want to assign to the VoIP devices
  connecting to this switch.
* *RADIUS -> Secret Passphrase*: `useStrongerSecret`
* *SNMP -> Version*: `v2c`
* *SNMP -> Community Read*: `public`
* *SNMP -> Community Write*: `private`

==== 802.1X commands

  show dot1x
  show dot1x users
