name: Apply configuration changes (configreload hard + restart radiusd-auth)
testcases:

- name: run_configreload_hard
  steps:
  - type: pf_configreload_hard

- name: restart_radiusd_auth_service
  steps:
  - type: pf_api_service_restart
    service: radiusd-auth
    time_to_sleep: 5
