---
# Device profiling tests using VirtualSwitch
## Validates that connecting Windows/iOS/Android devices
## correctly detects them via Fingerbank

- import_playbook: ../common/dev.yml
  when: lookup("env", "CI") != 'true'

- import_playbook: playbooks/configure.yml

# Render seed templates for configurator_bypass
- import_playbook: playbooks/render_seeds.yml

- import_playbook: playbooks/run_tests.yml
