---
# all variables added to:
# - /etc/environment
# - Ansible environment when running Venom tests
inventory__group_environment:
  PF_TEST_MGMT_INT: "{{ packetfence_install__mgmt_interface['id'] }}"
  PF_TEST_MGMT_IP: "{{ packetfence_install__mgmt_interface['ip'] }}"
  PF_TEST_MGMT_MASK: "{{ packetfence_install__mgmt_interface['mask'] }}"
  PSONO_CI_SERVER_URL: '{{ lookup("env","PSONO_CI_SERVER_URL")|default("https://psono.inverse.ca/server") }}'
  # lookup variables available to GitLab runner
  # defined in GitLab UI
  PSONO_CI_API_KEY_ID: '{{ lookup("env", "PSONO_CI_API_KEY_ID") }}'
  PSONO_CI_API_SECRET_KEY_HEX: '{{ lookup("env", "PSONO_CI_API_SECRET_KEY_HEX") }}'
  CI_VIRTUALSWITCH_USER: '{{ lookup("env", "CI_VIRTUALSWITCH_USER") }}'
  CI_VIRTUALSWITCH_PASSWORD: '{{ lookup("env", "CI_VIRTUALSWITCH_PASSWORD") }}'
  CI_VIRTUALSWITCH_BASE_URL: 'https://support.inverse.ca/~jgoimard/virtualswitch'
  CI_VIRTUALSWITCH_DEB_VERSION: '2.6.5-1'
  CI_VIRTUALSWITCH_RPM_VERSION: '2.6.5-1.el8'
  PATH: '/usr/local/go/bin:{{ ansible_env.PATH }}'
  CI: "{{ 'True ' if lookup('env', 'CI') else 'False ' }}"
