---
- name: Download Rocky official GPG key
  get_url:
    url: https://dl.rockylinux.org/pub/rocky/RPM-GPG-KEY-rockyofficial
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    mode: '0644'

- name: Ensure Rocky Linux BaseOS repo file (disabled by default)
  copy:
    dest: /etc/yum.repos.d/Rocky-BaseOS.repo
    content: |
      [baseos]
      name=Rocky Linux $releasever - BaseOS
      mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=BaseOS-$releasever
      gpgcheck=1
      enabled=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial

- name: Ensure Rocky Linux AppStream repo file (disabled by default)
  copy:
    dest: /etc/yum.repos.d/Rocky-AppStream.repo
    content: |
      [appstream]
      name=Rocky Linux $releasever - AppStream
      mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=AppStream-$releasever
      gpgcheck=1
      enabled=0
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial

- name: Install python3.11 using BaseOS and AppStream temporarily enabled
  command: >
    dnf install python3.11 --enablerepo=baseos,appstream -y

- name: Remove Rocky Linux repo files after installation
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/yum.repos.d/Rocky-AppStream.repo
    - /etc/yum.repos.d/Rocky-BaseOS.repo

- name: Get RHEL username using psonoci
  ansible.builtin.command:
    cmd: 'psonoci secret get {{ rhel_sub_psono_secret_id }} username'
  when: rhel_sub_psono_secret_id
  no_log: True
  register: reg_rhel_sub_register_username
  retries: 3
  delay: 10
  until: reg_rhel_sub_register_username is successful

- name: Get RHEL password using psonoci
  ansible.builtin.command:
    cmd: 'psonoci secret get {{ rhel_sub_psono_secret_id }} password'
  when: rhel_sub_psono_secret_id
  no_log: True
  register: reg_rhel_sub_register_password
  retries: 3
  delay: 10
  until: reg_rhel_sub_register_password is successful

- name: Remove Rocky GPG key after installation
  file:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
    state: absent
  
- name: Register RHEL subscription
  community.general.redhat_subscription:
    state: present
    username: '{{ reg_rhel_sub_register_username.stdout | d(rhel_subscription_user) }}'
    password: '{{ reg_rhel_sub_register_password.stdout | d(rhel_subscription_password) }}'
    auto_attach: true
  register: reg_rhel_sub_register_el
  retries: 3
  delay: 10
  until: reg_rhel_sub_register_el is successful
