---
- name: allow all on default interface for vagrant management
  blockinfile:
    path: "/usr/local/pf/conf/firewalld/firewalld-input.conf.inc"
    create: true
    owner: pf
    group: pf
    block: |
      # allow all ports for vagrant management
      ipv4 filter INPUT -100 -i {{ ansible_default_ipv4.interface }} -j ACCEPT
      # allow MailHog (SMTP and web interface) on management interface
      ipv4 filter INPUT -100 -i {{ packetfence_install__mgmt_interface["id"] }} --protocol tcp --match tcp --dport {{ mailhog__smtp_port }} --jump ACCEPT
      ipv4 filter INPUT -100 -i {{ packetfence_install__mgmt_interface["id"] }} --protocol tcp --match tcp --dport {{ mailhog__api_port }}  --jump ACCEPT
      # allow Smocker interface on management interface
      ipv4 filter INPUT -100 -i {{ packetfence_install__mgmt_interface["id"] }} --protocol tcp --match tcp --dport {{ smocker__port_config }} --jump ACCEPT
      # allow RADIUS mock ports on management interface
      ipv4 filter INPUT -100 -i {{ packetfence_install__mgmt_interface["id"] }} --protocol tcp --match tcp --dport {{ radius_mock__api_port }} --jump ACCEPT
      ipv4 filter INPUT -100 -i {{ packetfence_install__mgmt_interface["id"] }} --protocol tcp --match tcp --dport {{ radius_mock__radius_port }} --jump ACCEPT
    marker: "# {mark} ANSIBLE MANAGED BLOCK - vagrant"
