/**
* From lib/pf/constants/eap_type.pm
*/

export const pfEapType = {
  '33': 'MS-Authentication-TLV',
  '32': 'SecurID-EAP',
  '21': 'EAP-TTLS',
  '26': 'Microsoft-MS-CHAPv2',
  '2': 'Notification',
  '17': 'Cisco-LEAP',
  '1': 'Identity',
  '18': 'SIM',
  '30': 'DynamID',
  '16': 'Arcot-Systems-EAP',
  '44': 'Zonelabs',
  '25': 'PEAP',
  '27': 'MAKE',
  '28': 'CRYPTOCard',
  '40': 'DeviceConnect-EAP',
  '14': 'Defender-Token',
  '49': 'EAP-IKEv2',
  '24': 'EAP-3Com-Wireless',
  '10': 'DSS-Unilateral',
  '31': 'Rob-EAP',
  '35': 'EAP-Actiontec-Wireless',
  '11': 'KEA',
  '53': 'EAP-EVEv1',
  '48': 'EAP-SAKE',
  '42': 'EAP-MOBAC',
  '22': 'Remote-Access-Service',
  '46': 'EAP-PAX',
  '13': 'EAP-TLS',
  '23': 'AKA',
  '29': 'Cisco-MS-CHAPv2',
  '6': 'Generic-Token-Card',
  '50': 'EAP-AKA2',
  '39': 'SecuriSuite-EAP',
  '3': 'NAK',
  '36': 'Cogent-Biomentric-EAP',
  '51': 'EAP-GPSK',
  '9': 'RSA-Public-Key',
  '12': 'KEA-Validate',
  '41': 'EAP-SPEKE',
  '15': 'RSA-SecurID-EAP',
  '47': 'EAP-PSK',
  '38': 'EAP-HTTP-Digest',
  '52': 'EAP-PWD',
  '4': 'MD5-Challenge',
  '34': 'SentriNET',
  '37': 'AirFortress-EAP',
  '45': 'EAP-Link',
  '43': 'EAP-FAST',
  '19': 'SRP-SHA1',
  '5': 'One-Time-Password'
}
