= Installation Guide
////

    This file is part of the PacketFence project.

    See includes/global-attributes.asciidoc
    for authors, copyright and license information.

////
include::includes/global-attributes.asciidoc[]

== About this Guide

This guide covers PacketFence installation and day-to-day administration.

Find the latest version at https://packetfence.org/documentation/

=== Other sources of information

<<PacketFence_Clustering_Guide.asciidoc#,Clustering Guide>>::
  Covers installation in a clustered environment.
<<PacketFence_Developers_Guide.asciidoc#,Developer's Guide>>::
  Covers API, captive portal customization, application code customizations and support for new equipment.
<<PacketFence_Network_Devices_Configuration_Guide.asciidoc#,Network Devices Configuration Guide>>::
  Covers switches, WiFi controllers and access points configuration.
<<PacketFence_Upgrade_Guide.asciidoc#,Upgrade Guide>>::
  Covers compatibility changes, manual instructions and upgrade notes.
https://packetfence.org/news.html[PacketFence News]::
  Covers noteworthy features, improvements and bug fixes by release.

Package and release tarballs include these files.

== Introduction

PacketFence is a fully supported, trusted, Free and Open Source network access control (NAC) system. It features a captive portal for registration and remediation, centralized wired and wireless management, 802.1X support, layer-2 isolation of problematic devices, and integration with IDS, vulnerability scanners and firewalls. PacketFence effectively secures networks from small to very large heterogeneous environments. Visit https://packetfence.org for more details.

== System Requirements

include::installation/system_requirements.asciidoc[]

== Installation

include::installation/installation.asciidoc[]

== Getting Started

include::installation/getting_started.asciidoc[]

== Enabling the Captive Portal

include::installation/enabling_the_captive_portal.asciidoc[]

== Authentication Sources

include::installation/authentication_sources.asciidoc[]

== Introduction to Role-based Access Control

include::installation/introduction_to_role_based_access_control.asciidoc[]

== Supported Enforcement Modes

include::installation/enforcement/supported_enforcement_modes.asciidoc[]

== Adding Inline Enforcement to Existing Installation

include::installation/enforcement/inline.asciidoc[]

== Adding VLAN Enforcement to Existing Installation

include::installation/enforcement/out-of-band.asciidoc[]

== Troubleshooting PacketFence

include::installation/troubleshooting_packetfence.asciidoc[]

== Authentication Mechanisms

include::installation/authentication_mechanisms.asciidoc[]

== Advanced Portal Configuration

include::installation/advanced_portal_configuration.asciidoc[]

== Advanced Access Configuration

include::installation/advanced_access_configuration.asciidoc[]

== Advanced RADIUS Configuration

include::installation/advanced_radius_configuration.asciidoc[]

== Fingerbank Integration

include::installation/fingerbank_integration.asciidoc[]

== Network Devices Anomaly Detection

include::installation/network_devices_anomaly_detection.asciidoc[]

== Intrusion Detection System Integration

include::installation/intrusion_detection_system_integration.asciidoc[]

== Firewall SSO Integration

include::installation/firewall_sso_integration.asciidoc[]

== Performing Compliance Checks

include::installation/performing_compliance_checks.asciidoc[]

[[provision]]
== Integrating Provisioning Agents

include::installation/integrating_provisioning_agents.asciidoc[]

== PKI Integration

include::installation/pki_integration.asciidoc[]

== MFA Integration

include::installation/mfa_integration.asciidoc[]

== Best Practices

include::installation/best_practices.asciidoc[]

== Performance Optimizations

include::installation/performance_optimizations.asciidoc[]

== Advanced Network Topics

include::installation/advanced_network_topics.asciidoc[]

== Additional Integration

include::installation/additional_integration.asciidoc[]

== Advanced Topics

include::installation/advanced_topics.asciidoc[]

== Export/Import mechanism

include::installation/export_import_mechanism.asciidoc[]

== PacketFence Certificates (for v11.2 and later)

include::installation/certificate.asciidoc[]

// INCLUDES

include::includes/additional-info.asciidoc[]

include::includes/commercial-support.asciidoc[]

include::includes/license.asciidoc[]

[appendix]
== Quick Reference

=== Terms and Technologies

802.1X::
  <<#_authentication_mechanisms,Authentication Mechanisms>>, <<#_advanced_radius_configuration,Advanced RADIUS Configuration>>

AAA::
  <<#_authentication_sources,Authentication Sources>>, <<#_advanced_radius_configuration,Advanced RADIUS Configuration>>

ACL::
  <<#_introduction_to_role_based_access_control,Introduction to Role-based Access Control>>

AD::
  <<#_authentication_sources,Authentication Sources>>

API::
  <<#_advanced_topics,Advanced Topics>>

Authentication::
  <<#_authentication_sources,Authentication Sources>>, <<#_authentication_mechanisms,Authentication Mechanisms>>

Certificate::
  <<#_packetfence_certificates_for_v11_2_and_later,PacketFence Certificates (for v11.2 and later)>>

Compliance::
  <<#_performing_compliance_checks,Performing Compliance Checks>>

DHCP::
  <<#_advanced_network_topics,Advanced Network Topics>>

DNS::
  <<#_advanced_network_topics,Advanced Network Topics>>

EAP::
  <<#_authentication_mechanisms,Authentication Mechanisms>>, <<#_advanced_radius_configuration,Advanced RADIUS Configuration>>

Enforcement::
  <<#_supported_enforcement_modes,Supported Enforcement Modes>>, <<#_adding_inline_enforcement_to_existing_installation,Adding Inline Enforcement to Existing Installation>>

Fingerbank::
  <<#_fingerbank_integration,Fingerbank Integration>>

Firewall::
  <<#_firewall_sso_integration,Firewall SSO Integration>>

HTTP::
  <<#_advanced_portal_configuration,Advanced Portal Configuration>>

HTTPS::
  <<#_advanced_portal_configuration,Advanced Portal Configuration>>, <<#_packetfence_certificates_for_v11_2_and_later,PacketFence Certificates (for v11.2 and later)>>

IDS::
  <<#_intrusion_detection_system_integration,Intrusion Detection System Integration>>

Inline::
  <<#_adding_inline_enforcement_to_existing_installation,Adding Inline Enforcement to Existing Installation>>

LDAP::
  <<#_authentication_sources,Authentication Sources>>

MAC::
  <<#_authentication_mechanisms,Authentication Mechanisms>>

MFA::
  <<#_mfa_integration,MFA Integration>>

NAC::
  <<#_introduction,Introduction>>

Network::
  <<#_advanced_network_topics,Advanced Network Topics>>, <<#_network_devices_anomaly_detection,Network Devices Anomaly Detection>>

PEAP::
  <<#_authentication_mechanisms,Authentication Mechanisms>>, <<#_advanced_radius_configuration,Advanced RADIUS Configuration>>

PKI::
  <<#_pki_integration,PKI Integration>>

Portal::
  <<#_enabling_the_captive_portal,Enabling the Captive Portal>>, <<#_advanced_portal_configuration,Advanced Portal Configuration>>

Provisioning::
  <<#_integrating_provisioning_agents,Integrating Provisioning Agents>>

QoS::
  <<#_advanced_network_topics,Advanced Network Topics>>

RADIUS::
  <<#_advanced_radius_configuration,Advanced RADIUS Configuration>>, <<#_authentication_mechanisms,Authentication Mechanisms>>

RBAC::
  <<#_introduction_to_role_based_access_control,Introduction to Role-based Access Control>>

SAML::
  <<#_authentication_sources,Authentication Sources>>

SNMP::
  <<#_advanced_network_topics,Advanced Network Topics>>

SQL::
  <<#_advanced_topics,Advanced Topics>>

SSH::
  <<#_advanced_topics,Advanced Topics>>

SSL::
  <<#_packetfence_certificates_for_v11_2_and_later,PacketFence Certificates (for v11.2 and later)>>

SSO::
  <<#_firewall_sso_integration,Firewall SSO Integration>>

TLS::
  <<#_packetfence_certificates_for_v11_2_and_later,PacketFence Certificates (for v11.2 and later)>>, <<#_advanced_radius_configuration,Advanced RADIUS Configuration>>

TTLS::
  <<#_authentication_mechanisms,Authentication Mechanisms>>, <<#_advanced_radius_configuration,Advanced RADIUS Configuration>>

VLAN::
  <<#_adding_vlan_enforcement_to_existing_installation,Adding VLAN Enforcement to Existing Installation>>, <<#_supported_enforcement_modes,Supported Enforcement Modes>>

VPN::
  <<#_advanced_network_topics,Advanced Network Topics>>

WiFi::
  <<#_authentication_mechanisms,Authentication Mechanisms>>

== Appendix

include::installation/appendix.asciidoc[]

// vim: set syntax=asciidoc tabstop=2 shiftwidth=2 expandtab:
