= Clustering Quick Installation Guide
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left

// to display images directly on GitHub
ifdef::env-github[]
:imagesdir: ./images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Clustering_Guide-docinfo.xml for 
    authors, copyright and license information.

////

ifndef::env-github[]
include::includes/global-attributes.asciidoc[]
endif::[]

== About this Guide

This guide has been created to give a quick start to install active/active clustering in PacketFence 7+. This guide does not include advanced troubleshooting of the active/active clustering. Refer to the documentation of HAProxy and Keepalived for advanced features.

The latest version of this guide is available at https://packetfence.org/documentation/

=== Other sources of information

<<PacketFence_Developers_Guide.asciidoc#,Developer's Guide>>::
  Covers API, captive portal customization, application code customizations and instructions for supporting new equipment.
<<PacketFence_Installation_Guide.asciidoc#,Installation Guide>>::
  Covers installation and configuration of PacketFence.
<<PacketFence_Network_Devices_Configuration_Guide.asciidoc#,Network Devices Configuration Guide>>::
  Covers switches, WiFi controllers and access points configuration.
<<PacketFence_Upgrade_Guide.asciidoc#,Upgrade Guide>>::
  Covers compatibility related changes, manual instructions and general notes about upgrading.
link:https://packetfence.org/news.html[PacketFence News]
  Covers noteworthy features, improvements and bug fixes by release.

These files are included in the package and release tarballs.

//== Assumptions

ifdef::env-github[]
<<cluster/assumptions#assumptions, Assumptions>>
endif::[]
ifndef::env-github[]
include::cluster/assumptions.asciidoc[]
endif::[]

//== Cluster Setup

ifdef::env-github[]
<<cluster/cluster_setup#cluster-setup, Cluster Setup>>
endif::[]
ifndef::env-github[]
include::cluster/cluster_setup.asciidoc[]
endif::[]

//== Understanding the Galera cluster synchronization

ifdef::env-github[]
<<cluster/understanding_the_galera_cluster_synchronization#understanding-the-galera-cluster-synchronization, Understanding the Galera cluster synchronization>>
endif::[]
ifndef::env-github[]
include::cluster/understanding_the_galera_cluster_synchronization.asciidoc[]
endif::[]

//== Troubleshooting a cluster

ifdef::env-github[]
<<cluster/troubleshooting_a_cluster#troubleshooting-a-cluster, Troubleshooting a cluster>>
endif::[]
ifndef::env-github[]
include::cluster/troubleshooting_a_cluster.asciidoc[]
endif::[]

//== Maintenance and Operations

ifdef::env-github[]
<<cluster/maintenance_and_operations#maintenance-and-operations, Maintenance and Operations>>
endif::[]
ifndef::env-github[]
include::cluster/maintenance_and_operations.asciidoc[]
endif::[]

//== Layer 3 clusters

ifdef::env-github[]
<<cluster/layer_3_clusters#layer-3-clusters, Layer 3 clusters>>
endif::[]
ifndef::env-github[]
include::cluster/layer_3_clusters.asciidoc[]
endif::[]

//== Advanced configuration

ifdef::env-github[]
<<cluster/advanced_configuration#advanced-configuration, Advanced configuration>>
endif::[]
ifndef::env-github[]
include::cluster/advanced_configuration.asciidoc[]
endif::[]

// INCLUDES

ifdef::env-github[]
<<includes/additional-info#additional-information, Additional Information>>
endif::[]
ifndef::env-github[]
include::includes/additional-info.asciidoc[]
endif::[]

ifdef::env-github[]
<<includes/commercial-support, Additional Info>>
endif::[]
ifndef::env-github[]
include::includes/commercial-support.asciidoc[]
endif::[]

ifdef::env-github[]
<<includes/license#gnu-free-documentation-license, License>>
endif::[]
ifndef::env-github[]
include::includes/license.asciidoc[]
endif::[]

//== Appendix

ifdef::env-github[]
<<cluster/appendix#appendix, Appendix>>
endif::[]
ifndef::env-github[]
include::cluster/appendix.asciidoc[]
endif::[]
