Rapid7 InsightVM Nexpose: Quick Integration Guide
-------------------------------------------------
:doctype: book
:toc: left

include::includes/global-attributes.asciidoc[]

////

    This file is part of the PacketFence project.

    See PacketFence_Administration_Guide-docinfo.xml for authors, copyright 
    and license information.

////

About this Guide
----------------

This guide has been created in order to help you with the configuration of Rapid7 InsighVM Nexpose and PacketFence, to provide information and actions about devices compliance before and during network access.


Assumptions
-----------
* You have a configured PacketFence server environment with working test equipment.
* You have a Centos 7 server, ready and updated, we will use it as the 'Rapid7 InsightVM' server.
* You have created an account at https://www.rapid7.com/[Rapid7] and downloaded the https://www.rapid7.com/products/insightvm/[InsightVM] binaries.
* You have, at least, a trial licence.

Installation
------------

Step 1: Rapid7 Insight Configuration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

How to configure Rapid7 InsightVM Nexpose Server to send data to the PacketFence server in a way it can understand and process it.

WARNING: Disable the firewalld service, the iptables services, SELinux, and ... others filtering services.

Application Installation
^^^^^^^^^^^^^^^^^^^^^^^^
* Install the InsighVM application 
** https://insightvm.help.rapid7.com/docs/installing-in-linux-environments#section-installing-in-red-hat

* Run the application 
** https://insightvm.help.rapid7.com/docs/running-the-application#section-managing-the-application-in-linux

* Logon to the server: _https://'YourRapid7ServerIP:3780_

First Scan Creation
^^^^^^^^^^^^^^^^^^^
* Create a new site by clicking the *Create -> Site* 
* After naming the new site, create the new assets: *Site configuration -> Assets*
* In Include, create the list of assets you want to audit:
:===
What you will write:What Nexpose will understand
10.0.0.0/24:10.0.0.1-10.0.0.254
10.0.0.1-10.0.0.254:10.0.0.1-10.0.0.254
:===

* In *Exclude*, put all the assets you want to exclude from the previous ranges.
* In the upper *Menu*, select *Templates* and define the scope of the audit you want.
* In the *Menu*, select *Engines* and define the engine, depending on the licence and scope you have.

Sending syslog information to PacketFenc
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
* On the left, create a new alert.
* In the *Menu*, select now *Alerts*

|===
|*Enable*: Must be checked. 

*Alert Name*: Rsyslog to PacketFence or else.

*Maximum Alerts to send*: blank (none)

*Scan events*: Check all.

*Vulnerability Events*: _Any severity_ ; Check as well _Confirmed_, _Unconfirmed_, _Potential_

*Notification Method*: Select _Syslog message_

*Syslog Server*: "PacketFence cluster VIP or server IP for a standalone"  
|===

In the *Menu*, select now *Schedule*, and define the schedules of your audits.


Step 2: PacketFence Configuration
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

"What needs to be done on the PacketFence Server to understand and take action about endpoints containing threats"

PacketFence changes to handle Nexpose syslog information
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

WARNING: If you are using a PacketFence cluster, you will need to do these steps on all your PacketFence servers.

* Logon to PacketFence Server with a _ssh_ terminal.
* Create the fifo pipe file that PacketFence will use to get data from Nexpose
 
 mkfifo /usr/local/pf/var/run/nexpose_pipe

* Create a new file named /etc/rsyslog.d/nexpose-log.conf.

 # rsyslog conf for Rapid7 Nexpose server logs reception
 if $programname == 'Nexpose' then /usr/local/pf/var/run/nexpose_pipe
 & ~

* Modify /etc/rsyslog.conf to accept syslogs data on 'udp 514'
** Uncomment the two lines:

 $ModLoad imudp
 $UDPServerRun 514

* Restart the 'rsyslog' service
** Run this command:
  
  service rsyslog restart

At this point PacketFence must be able to get the Nexpose audit results.

TIP: You can see if the Nexpose server is sending to the right server by monitoring both sides traffic, with a 'tcpdump -i any dst host YOUR_PACKETFENCE_SERVERI' on your Rapid7 Nexpose server and 'tcpdump -i any port 514' on the PacketFence server.

Integrating with PacketFence violation system
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Let's give PacketFence the Nexpose parser it needs to detect Nexpose events ::
* Logon to PacketFence server with a browser on the PacketFence admin interface. 
** _https://YOUR_PACKETFENCE_SERVER_IP:1443_

* Go to *Configuration -> Integration -> Syslog parsers*
* On the drop list 'ADD SYSLOG PARSER', take 'Nexpose'
* As Detector, put the name of your choice for this parser.
* In Alert pipe, put the 'absolute' path to our nexpose pipe

  /usr/local/pf/var/run/nexpose_pipe

* Click on 'SAVE'.

Once done, we need to restart the good services ::
* Restart the 'pfdetect' and the 'pfqueue' service.
----
/usr/local/pf/pfcmd service pfdetect restart
/usr/local/pf/pfcmd service pfqueue restart
----

Now that PacketFence is properly configured to receive information from Nexpose, lets configure it to perform some actionsi ::
* In the PacketFence GUI, go to *Configuration -> Compliance -> Violations*
* Go down on the page to the end of the section and note the last violation ID XXXXXXX
* Click on *ADD VIOLATION*

|===
|*Definition*
|*Enable*: Set it to *ON* 

*Identifier*: Use the previously noted violation ID and add 1 to it. (But you can use whatever you want.)

*Action*: This is where you put what you want PacketFence to do, in this case.
|===


|===
|*Triggers*
|Click on the plus *(+)*, on the right side of the page.

On the second line, choose the appropriate trigger between "*nexpose_event_contains*" or "*nexpose_event_start_with*"

Choose "nexpose_event_contains" if you know, for example, the "*Common Vulnerabilities and Exposures*" you want to take action on.

| For "*nexpose_event_contains*": You can put there the CVE or the vlnerability name you are looking for.

For "*nexpose_event_start_with*": Put there the full vulnerability name you can find in the Nexpose report, on the Nexpose GUI

| Click on *ADD*, then *SAVE*

INFO: You can only have one trigger, for one violation.

|===


For more info on violation actions, go to the _PacketFence Administration Guide_, in _Blocking malicious activities with violations_ 




