= PacketFence Developer's Guide
////

    This file is part of the PacketFence project.

    See includes/global-attributes.asciidoc
    for authors, copyright and license information.

////
include::includes/global-attributes.asciidoc[]

== About this Guide

This guide helps modify PacketFence for specific needs and covers adding support for new switches.

Find the latest version at https://packetfence.org/documentation/.

=== Other sources of information

https://www.packetfence.org/doc/PacketFence_Clustering_Guide.html[Clustering Guide]::
  Covers installation in a clustered environment.
https://www.packetfence.org/doc/PacketFence_Installation_Guide.html[Installation Guide]::
  Covers installation and configuration of PacketFence.
https://www.packetfence.org/doc/PacketFence_Network_Devices_Configuration_Guide.html[Network Devices Configuration Guide]::
  Covers switches, WiFi controllers and access points configuration.
https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html[Upgrade Guide]::
  Covers compatibility changes, manual instructions and upgrade notes.
https://packetfence.org/news.html[PacketFence News]::
  Covers noteworthy features, improvements and bug fixes by release.

Package and release tarballs include these files.

== Creating a new Switch via a Template

include::developer/template_switches.asciidoc[]

== Documentation

include::developer/documentation_info.asciidoc[]

== Development environment setup

include::developer/dev_env_setup.asciidoc[]

== Administration GUI development setup

include::developer/admin_gui.asciidoc[]

== Golang environment

include::developer/go/README.asciidoc[]

== Code conventions

include::developer/code_conventions.asciidoc[]

== HTTP JSON API

include::developer/http_json_api.asciidoc[]

== Customizing PacketFence

include::developer/customizing_packetfence.asciidoc[]

== SNMP

include::developer/snmp.asciidoc[]

== Supporting new network hardware

include::developer/supporting_new_network_hardware.asciidoc[]

== PacketFence builds

include::developer/packer/README.asciidoc[]

== Developer recipes

include::developer/developer_recipes.asciidoc[]

== Containers recipes

include::developer/containers_recipes.asciidoc[]

== Running tests

include::developer/tests/README.asciidoc[]

include::developer/integration_tests/README.asciidoc[]

== Contributing

include::developer/contributing.asciidoc[]


// INCLUDES

include::includes/additional-info.asciidoc[]

include::includes/commercial-support.asciidoc[]

include::includes/license.asciidoc[]


// vim: set syntax=asciidoc tabstop=2 shiftwidth=2 expandtab:
