= Network Devices Configuration Guide
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left

// to display images directly on GitHub
ifdef::env-github[]
:imagesdir: ./images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Network_Devices_Configuration_Guide-docinfo.xml for 
    authors, copyright and license information.

////

ifndef::env-github[]
include::includes/global-attributes.asciidoc[]
endif::[]

== About this Guide

This guide covers the configuration of network devices in order to integrate them with PacketFence in VLAN enforcement. Switches, wireless controllers and wireless access points are all considered network devices in PacketFence's terms.

The latest version of this guide is available at https://packetfence.org/documentation/

=== Other sources of information

<<PacketFence_Clustering_Guide.asciidoc#,Clustering Guide>>::
  Covers installation in a clustered environment.
<<PacketFence_Developers_Guide.asciidoc#,Developer's Guide>>::
  Covers API, captive portal customization, application code customizations and
  instructions for supporting new equipment.
<<PacketFence_Installation_Guide.asciidoc#,Installation Guide>>::
  Covers installation and configuration of PacketFence.
<<PacketFence_Upgrade_Guide.asciidoc#,Upgrade Guide>>::
  Covers compatibility related changes, manual instructions and general notes
  about upgrading.
link:https://packetfence.org/news.html[PacketFence News]
  Covers noteworthy features, improvements and bug fixes by release.

These files are included in the package and release tarballs.

== Note on Inline enforcement support

There is no need to follow the instructions in this guide if you plan on deploying in inline enforcement, except RADIUS inline. In this case all you need to do is to have a flat layer 2 network up to PacketFence's inline interface with no other gateway available for devices to reach out to the Internet. 

This technique is usually used when your network hardware doesn't support VLAN enforcement.

== Note on RADIUS accounting

Enabling RADIUS accounting on your network devices will increase significantly your database size and can cause performance issues. You should be aware of this and use accounting only if you really need it.

//== List of supported Network Devices

ifdef::env-github[]
<<network/list_of_supported_network_devices#list-of-supported-network-devices, List of supported Network Devices>>
endif::[]
ifndef::env-github[]
include::network/list_of_supported_network_devices.asciidoc[]
endif::[]

//== Switch configuration

ifdef::env-github[]
<<network/switch_configuration#switch-configuration, Switch configuration>>
endif::[]
ifndef::env-github[]
include::network/switch_configuration.asciidoc[]
endif::[]

//== Wireless Controllers and Access Point Configuration

ifdef::env-github[]
<<network/wireless_controllers_and_access_point_configuration#wireless-controllers-and-access-point-configuration, Wireless Controllers and Access Point Configuration>>
endif::[]
ifndef::env-github[]
include::network/wireless_controllers_and_access_point_configuration.asciidoc[]
endif::[]

//== VPN Configuration

ifdef::env-github[]
<<network/vpn_configuration#vpn-configuration, VPN Configuration>>
endif::[]
ifndef::env-github[]
include::network/vpn_configuration.asciidoc[]
endif::[]

// INCLUDES

ifdef::env-github[]
<<includes/additional-info#additional-information, Additional Information>>
endif::[]
ifndef::env-github[]
include::includes/additional-info.asciidoc[]
endif::[]

ifdef::env-github[]
<<includes/commercial-support, Additional Info>>
endif::[]
ifndef::env-github[]
include::includes/commercial-support.asciidoc[]
endif::[]

ifdef::env-github[]
<<includes/license#gnu-free-documentation-license, License>>
endif::[]
ifndef::env-github[]
include::includes/license.asciidoc[]
endif::[]

// vim: set syntax=asciidoc tabstop=2 shiftwidth=2 expandtab:
