PacketFence: Ruckus Quick Installation Guide
============================================
:encoding: UTF-8
:lang: en
:doctype: book

////

    This file is part of the PacketFence project.

    See PacketFence_Ruckus_Quick_Installation_Guide-docinfo.xml for
    authors, copyright and license information.

////

include::includes/global-attributes.asciidoc[]

About this Guide
----------------
This guide as been created in order to help sales engineers, product managers, or network specialist to demonstrate the PacketFence capabilities on-site with an existing or potential customer.  It can also provide guidelines to setup a proof of concept for a potential PacketFence deployment using the Ruckus equipment.

The instructions are based on version {release_version} of the PacketFence ZEN VMware Appliance.

Assumptions
-----------
* Your customer will provide the network hardware (switch, wires, etc) to interconnect this PoC setup
* The PC that will handle the ZEN VM is using CentOS/RHEL 5 on 64bit hardware.
* Ruckus ZoneDirector is loaded with firmware 9.3.1.0 build 9
* Ruckus ZoneDirector is factory default

Quick Deployment
----------------
Step 1: Pre-load
~~~~~~~~~~~~~~~~
To begin the deployment process, you need to download and install the PacketFence ZEN Desktop appliance to your laptop.  Due to some network drivers limitations, you need to run RHEL/CentOS 5 on your PC, or Ubuntu.  You CANNOT run the VM on a Windows host.

Install VMWare Player
^^^^^^^^^^^^^^^^^^^^^
First of all, you need to get VMware Player.  To download the product, simply go to http://www.vmware.com/download/player, and click on the download link.  You will require to register in order to download the product.

Once downloaded, you need to run the bundle file.  As root, use the following command :

   sh VMware-Player-4.0.2-591240.x86_64.bundle

Follow the prompt to finish the install procedure.

NOTE: For more information about the VMWare Player installation, you may refer to the page 12 of the "Getting Started with VMware Player" guide available at https://www.vmware.com/pdf/vmware_player40.pdf.

Download the PacketFence ZEN Desktop Appliance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
To download the PacketFence ZEN Desktop Appliance, visit http://www.packetfence.org/download/vmware_appliance_zen.html under the Desktop Version section.  Click on the link to start your download.  Once downloaded, extract the zip file.

Import the PacketFence ZEN Desktop Appliance
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
To import the PacketFence ZEN Desktop appliance, start the VMware Player first :

   vmplayer &

This should show a VMware Player window.  Then, go to File -> Open a Virtual Machine.  Browse for the PacketFence ZEN vmx file, and click Open.

NOTE: For more information about importing a VM into VMware Player, please refer to page 22 of the "Getting Started with VMware Player" guide available at https://www.vmware.com/pdf/vmware_player40.pdf.

Step 2: Configure Network and PacketFence
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The next step is the network setup and the PacketFence configuration.  The following step is usually performed when you arrive at a customer site.  Sometimes, you will know the network settings in advance, sometimes not.  If you want to save time, you should ask/tell the client what is needed in order to have the demonstration running smoothly.  That way, you will be able to preconfigure the PacketFence VM prior arrival.

Preliminary Questions
^^^^^^^^^^^^^^^^^^^^^
Here is a quick list of questions to ask to a customer in order to build workable PacketFence configuration files :

1. What is the VLAN ID and subnet to be used for a registration VLAN? (ie. VLAN ID 2, Subnet 192.168.2.0/24)
2. What is the VLAN ID and subnet to be used for an isolation VLAN? (ie. VLAN ID 3, Subnet 192.168.3.0/24)
3. What is the VLAN ID and subnet of the production VLAN? (ie. VLAN ID 10, Subnet 192.168.10.0/24)
4. A list of production DHCPs (for rogue DHCP detection)

Steps for the customer
^^^^^^^^^^^^^^^^^^^^^^
Some steps needs to be taken by the customer for having the network ready.  Here is a list of what we think should be ready for a demo :

* 1 TRUNK port to connect the demonstration PC, the native VLAN is a management VLAN that will be used to talk with the AP and the VM
* 1 TRUNK port to connect the controller
* 1 TRUNK port to connect the AP
* 1 management ACCESS port to connect another PC to access the PacketFence administrative UI.

Moving away from Inline to VLAN enforcement
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Our ZEN Appliance is configured to do Inline enforcement at first place.  We need to modify the configurations a bit in order to do VLAN enforcement.  Let us guide you through the process.

Start the PacketFence Appliance. The first time VMware Player ask you if the Virtual Machine has been copied or moved; answer "I copied it".
Login the Appliance using the default credentials, and stop the PacketFence service while doing the configuration changes:

   service packetfence stop

NOTE: Default credentials are listed in the PacketFence ZEN Administration Guide at Page 8.

Modify networking scripts
+++++++++++++++++++++++++
By default, networking is configured with 1 DHCP management interface (eth0), and one inline interface (eth0.200).  We need to disable the inline interface, and add the registration/isolation interface.

First, let's disable the inline interface.  In /etc/sysconfig/network-scripts/ifcfg-eth0.200, change the ONBOOT flag to "no":

   DEVICE=eth0.200
   VLAN=yes
   ONBOOT=no
   IPADDR=192.168.200.10
   NETMASK=255.255.255.0
   MTU=1442
   
Next, depending on the answers to Q1 to Q3, we need to enable the proper VLAN interface on the appliance.  Let's assume for now that

* Registration is VLAN ID 2, with subnet 192.168.2.0/24
* Isolation is VLAN ID 3, with subnet 192.168.3.0/24
* Normal is VLAN ID 10, with subnet 192.168.10.0/24

Let's see how the configuration would look.  So, /etc/sysconfig/network-scripts/ifcfg-eth0.2 :

   DEVICE=eth0.2
   VLAN=yes
   BOOTPROTO=static
   ONBOOT=yes
   IPADDR=192.168.2.10
   NETMASK=255.255.255.0
   MTU=1442

Now, /etc/sysconfig/network-scripts/ifcfg-eth0.3 :

   DEVICE=eth0.3
   VLAN=yes
   BOOTPROTO=static
   ONBOOT=yes
   IPADDR=192.168.3.10
   NETMASK=255.255.255.0
   MTU=1442

Finally, /etc/sysconfig/network-scripts/ifcfg-eth0.10 :

   DEVICE=eth0.10
   VLAN=yes
   BOOTPROTO=static
   ONBOOT=yes
   IPADDR=192.168.10.10
   NETMASK=255.255.255.0
   MTU=1442

CAUTION: Make sure the production IP is not existing on another node and that the PacketFence Appliance is connected to the network by a bridged interface

When done, restart the networking services (or reboot) using

   service network restart

Modify /usr/local/pf/conf/pf.conf
+++++++++++++++++++++++++++++++++
Now that we have the networking side covered, let's hop on the PacketFence side.  First thing to modify is pf.conf.  Again, we need to remove the inline configuration and add the VLAN enforcement configuration.

First, remove (or comment) the inline interface block

   [interface eth0.200]
   ip=192.168.200.10
   mask=255.255.255.0
   type=internal,monitor
   enforcement=inline
   gateway=192.168.200.10

Next, add the VLAN enforcement interface blocks

   [interface eth0.2]
   ip=192.168.2.10
   mask=255.255.255.0
   type=internal
   enforcement=vlan
   gateway=192.168.2.10

   [interface eth0.3]
   ip=192.168.3.10
   mask=255.255.255.0
   type=internal
   enforcement=vlan
   gateway=192.168.3.10

   [interface eth0.10]
   ip=192.168.10.10
   mask=255.255.255.0
   type=dhcp-listener,monitor
   gateway=192.168.10.1

Review the `[interface eth0]` block as well.  You need to make sure the IP and subnet information is properly configured for your management network.

Finally, adjust the general.domain, and general.hostname to your own preferred name.  Also adjust general.dhcpservers with the answers provided by the customer for Question 4.

Save the file when done.

Modify /usr/local/pf/conf/networks.conf
+++++++++++++++++++++++++++++++++++++++
This other configuration file needs to be adjusted as well.  Same principle, we remove the Inline network lines and replace them by the VLAN registration and isolation networks.

So let's remove the Inline network lines.  Remove or comment to following

   [192.168.200.0]
   type=inline
   netmask=255.255.255.0
   gateway=192.168.200.10
   dns=4.2.2.2
   dhcp_start=192.168.200.11
   dhcp_end=192.168.200.254
   dhcp_default_lease_time=300
   dhcp_max_lease_time=600
   named=disabled
   dhcpd=enabled
   next_hop=
   domain-name=nac.zen.packetfence.org

Now, let's add the VLAN registration and isolation network definitions

   [192.168.2.0]
   type=vlan-registration
   netmask=255.255.255.0
   gateway=192.168.2.10
   dns=192.168.2.10
   dhcp_start=192.168.2.11
   dhcp_end=192.168.2.254
   dhcp_default_lease_time=300
   dhcp_max_lease_time=600
   named=enabled
   dhcpd=enabled
   next_hop=
   domain-name=registration.zen.packetfence.org

   [192.168.3.0]
   type=vlan-isolation
   netmask=255.255.255.0
   gateway=192.168.3.10
   dns=192.168.3.10
   dhcp_start=192.168.3.11
   dhcp_end=192.168.3.254
   dhcp_default_lease_time=300
   dhcp_max_lease_time=600
   named=enabled
   dhcpd=enabled
   next_hop=
   domain-name=isolation.zen.packetfence.org

Save the file when done.

Modify /usr/local/pf/conf/switches.conf
+++++++++++++++++++++++++++++++++++++++
Adjust switches.conf.  In the `[default]` switch, make sure the VLAN names are properly setup, see below:

   [default]
   vlans = 2,3,4,10
   normalVlan = 10
   registrationVlan = 2
   isolationVlan = 3
   macDetectionVlan = 4   #This one is NOT used
   guestVlan = 5          #This one is NOT used

NOTE: If you need more information about custom VLAN assignment flows (ie. usage of the guestVlan), please see page 9 of the PacketFence Developer's Guide.

At the end of the file, add your Ruckus switch definition.  Ask the customer for the IP to use on the management network for the controller, and replace the RUCKUS_MANAGEMENT_IP with it in the block below.  You can remove the `[10.0.10.2]` and `[10.0.10.3]` switch blocks.

   [RUCKUS_MANAGEMENT_IP]
   type = Ruckus
   mode = production
   radiusSecret = aSecurePassword
   SNMPVersion = 2c
   SNMPCommunityRead = ruckusRead
   SNMPCommunityWrite = ruckusWrite

Modify /etc/raddb/users
+++++++++++++++++++++++
Last step for PacketFence, adjust the users file by adding the demouser to test 802.1x connection.

   demouser Cleartext-Password := demouser

Save the config, and start PacketFence!

Step 3: Configure Ruckus
~~~~~~~~~~~~~~~~~~~~~~~~
This section will discuss about the configuration of your Ruckus controller in order to use it with our configured PacketFence.

Connect APs and Controller
^^^^^^^^^^^^^^^^^^^^^^^^^^
First thing to do is to connect the controller and the AP.  Like we saw in Step 2, we should have 1 TRUNK port for the controller and 1 TRUNK port for the AP.  Connect them appropriately.

Provision the controller
^^^^^^^^^^^^^^^^^^^^^^^^
By default, the controller will come with the management IP set to 192.168.0.2.  You need to connect to it using the default credentials, and change its management IP accordingly.  Make sure also the firmware is at least 9.3.1.0 build 9 for full PacketFence support.

NOTE:  Please refer to the Ruckus ZoneDirector Quick Start Guide available at http://support.ruckuswireless.com/documents/35-zonedirector-quick-start-guide

Setup the SSIDs
^^^^^^^^^^^^^^^
For this guide, we will show you how to configure one open SSID with RADIUS mac filtering, and one secure SSID using WPA2-Enterprise.

Login your controller using the admin credentials.  You should see the Dashboard.  Click on the Configure pane, and follow the following steps.

Configure the AAA Servers
+++++++++++++++++++++++++
On the left menu, click on AAA Servers.  We need to add the PacketFence ZEN Desktop Appliance here.  Click on the Create New button, and provide those information:

   Name: zen_auth
   Type: RADIUS
   Auth Method: PAP
   IP Address : Management IP of the VM
   Port: 1812
   Shared Secret: aSecurePassword
   Confirm Secret: aSecurePassword 

Click OK to save the server.  Repeat the step to add PacketFence ZEN as a accounting server.  This step is *mandatory* otherwise RADIUS CoA will fail.

   Name: zen_accounting
   Type: RADIUS Accounting
   IP Address: Management IP of the VM
   Port: 1813
   Shared Secret: aSecurePassword
   Confirm Secret: aSecurePassword

Click OK to save the server.  You should see both authentication and accounting RADIUS servers in the list.

Configure the Open SSID
+++++++++++++++++++++++
On the left menu, click on WLAN.  Click the Create New button, and add the following information.  If you do not see the line, it means that you should leave the setting to default value:

   Name/ESSID: DemoOpen
   Decription: Open SSID for PoC
   Type: Standard Usage
   Authentication Method: MAC Address
   Encryption Options: None
   Authentication Server: zen_auth
   
   Expend Advanced Options:
   Accounting Server: zen_accounting
   Access VLAN: Select Enable Dynamic VLAN

Click OK to save the WLAN.

Configure the Secure SSID
+++++++++++++++++++++++++
On the left menu, click on WLAN.  Click the Create New button, and add the following information.  If you do not see the line it means that you should leave the setting to default value:

   Name/ESSID: DemoSecure
   Decription: Secure SSID for PoC
   Type: Standard Usage
   Authentication Method: 802.1X EAP
   Encryption Options: WPA2/AES
   Authentication Server: zen_auth
   
   Expend Advanced Options:
   Accounting Server: zen_accounting                                 
   Access VLAN: Select Enable Dynamic VLAN

Click OK to save the WLAN.

Configure SNMP
^^^^^^^^^^^^^^
Last step, we need to configure the SNMP to add a valid read community string.  Click on the Configure pane, and on System.  Expend the Network Management section, and look for the SNMPv2 Agent section.

   Select Enable SNMP Agent
   System Contact: your@email.com
   System Location: Customer Inc, Floor 2
   SNMP RO community: ruckusRead
   SNMP RW community: ruckusWrite

Step 4: Configuration of windows 7 client for DemoSecure
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In `Control Panel\Network and Internet\Manage Wireless Networks`, click on Add.
Click Manually create a network profile

   Network name: DemoSecure
   Security type WPA2-Entreprise
   Encryption AES

Next, Change connection settings. On Security tab, click Settings, uncheck Validate server certificate.
On the same tab click Configure and uncheck Automatically use my Windows logon name and password.
Return on Security tab and click on Advanced settings. On 802.1X settings , click on Specify authentication mode and select User authentication.
On 802.11 settings uncheck Enable Pairwise Master Key (PMK) caching.
Validate all the modification and click on close.

Step 5: Test and Demonstrate
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Congratulations, you have everything setup and ready!  If your setup is properly configured, you should be able to :

* reach (ping) the controller from the PacketFence VM
* see the DemoOpen, and DemoSecure SSIDs
* login the PacketFence administrative UI (https://management_IP:1443)

NOTE: Configured username/password for device registration, 802.1X, and to login the administrative UI are also listed in the PacketFence ZEN Administration Guide at page 8

