= Clustering Quick Installation Guide
////

    This file is part of the PacketFence project.

    See includes/global-attributes.asciidoc
    for authors, copyright and license information.

////
include::includes/global-attributes.asciidoc[]

== About this Guide

This guide provides quick installation steps for active/active clustering in PacketFence 7+. Advanced troubleshooting is not covered. Refer to HAProxy and Keepalived documentation for advanced features.

Find the latest version at https://packetfence.org/documentation/

=== Other sources of information

https://www.packetfence.org/doc/PacketFence_Developers_Guide.html[Developer's Guide]::
  Covers API, captive portal customization, application code customizations and instructions for supporting new equipment.
https://www.packetfence.org/doc/PacketFence_Installation_Guide.html[Installation Guide]::
  Covers installation and configuration of PacketFence.
https://www.packetfence.org/doc/PacketFence_Network_Devices_Configuration_Guide.html[Network Devices Configuration Guide]::
  Covers switches, WiFi controllers and access point configuration.
https://www.packetfence.org/doc/PacketFence_Upgrade_Guide.html[Upgrade Guide]::
  Covers compatibility changes, manual instructions and general upgrade notes.
https://packetfence.org/news.html[PacketFence News]::
  Covers noteworthy features, improvements and bug fixes by release.


Package and release tarballs include these files.

== Assumptions

include::cluster/assumptions.asciidoc[]

== Cluster Setup

include::cluster/cluster_setup.asciidoc[]

== Understanding the Galera cluster synchronization

include::cluster/understanding_the_galera_cluster_synchronization.asciidoc[]

== Troubleshooting a cluster

include::cluster/troubleshooting_a_cluster.asciidoc[]

== Maintenance and Operations

include::cluster/maintenance_and_operations.asciidoc[]

== Layer 3 clusters

include::cluster/layer_3_clusters.asciidoc[]

== Advanced configuration

include::cluster/advanced_configuration.asciidoc[]

== Troubleshooting Clusters

include::troubleshooting/mariadb_galera_sync.asciidoc[]

include::troubleshooting/cluster_recovery.asciidoc[]

include::troubleshooting/service_failures.asciidoc[]

include::troubleshooting/database_connectivity.asciidoc[]

include::troubleshooting/network_connectivity.asciidoc[]

include::troubleshooting/authentication_failures.asciidoc[]

include::troubleshooting/radius_debugging.asciidoc[]

include::troubleshooting/log_files.asciidoc[]

include::troubleshooting/performance_issues.asciidoc[]

// INCLUDES

include::includes/additional-info.asciidoc[]

include::includes/commercial-support.asciidoc[]

include::includes/license.asciidoc[]


== Appendix

include::cluster/appendix.asciidoc[]
