= Network Devices Configuration Guide
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left

// to display images directly on GitHub
ifdef::env-github[]
:imagesdir: images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Network_Devices_Configuration_Guide-docinfo.xml for 
    authors, copyright and license information.

////

include::includes/global-attributes.asciidoc[]

== About this Guide

This guide covers the configuration of network devices in order to integrate 
them with PacketFence in VLAN enforcement. Switches, wireless controllers and 
wireless access points are all considered network devices in PacketFence's 
terms.

The latest version of this guide is available at https://packetfence.org/documentation/

=== Other sources of information

<<PacketFence_Clustering_Guide.asciidoc#,Clustering Guide>>::
  Covers installation in a clustered environment.
<<PacketFence_Developers_Guide.asciidoc#,Developer's Guide>>::
  Covers API, captive portal customization, application code customizations and
  instructions for supporting new equipment.
<<PacketFence_Installation_Guide.asciidoc#,Installation Guide>>::
  Covers installation and configuration of PacketFence.
<<PacketFence_Upgrade_Guide.asciidoc#,Upgrade Guide>>::
  Covers compatibility related changes, manual instructions and general notes
  about upgrading.
<<PacketFence_News.asciidoc#,NEWS>>::
  Covers noteworthy features, improvements and bug fixes by release.

These files are included in the package and release tarballs.

== Note on Inline enforcement support

include::network/note_on_inline_enforcement_support.asciidoc[]

== Note on RADIUS accounting

include::network/note_on_radius_accounting.asciidoc[]

== List of supported Network Devices

include::network/list_of_supported_network_devices.asciidoc[]

== Switch configuration

include::network/switch_configuration.asciidoc[]

== Wireless Controllers and Access Point Configuration

include::network/wireless_controllers_and_access_point_configuration.asciidoc[]

== VPN Configuration

include::network/vpn_configuration.asciidoc[]

// INCLUDES

include::includes/additional-info.asciidoc[]

include::includes/commercial-support.asciidoc[]

include::includes/license.asciidoc[]

// vim: set syntax=asciidoc tabstop=2 shiftwidth=2 expandtab:
