= Clustering Quick Installation Guide
////

    This file is part of the PacketFence project.

    See includes/global-attributes.asciidoc
    for authors, copyright and license information.

////
include::includes/global-attributes.asciidoc[]

== About this Guide

This guide has been created to give a quick start to install active/active clustering in PacketFence 7+. This guide does not include advanced troubleshooting of the active/active clustering. Refer to the documentation of HAProxy and Keepalived for advanced features.

The latest version of this guide is available at https://packetfence.org/documentation/

=== Other sources of information

<<PacketFence_Developers_Guide.asciidoc#,Developer's Guide>>::
  Covers API, captive portal customization, application code customizations and instructions for supporting new equipment.
<<PacketFence_Installation_Guide.asciidoc#,Installation Guide>>::
  Covers installation and configuration of PacketFence.
<<PacketFence_Network_Devices_Configuration_Guide.asciidoc#,Network Devices Configuration Guide>>::
  Covers switches, WiFi controllers and access points configuration.
<<PacketFence_Upgrade_Guide.asciidoc#,Upgrade Guide>>::
  Covers compatibility related changes, manual instructions and general notes about upgrading.
link:https://packetfence.org/news.html[PacketFence News]
  Covers noteworthy features, improvements and bug fixes by release.

These files are included in the package and release tarballs.

== Assumptions

include::cluster/assumptions.asciidoc[]

== Cluster Setup

include::cluster/cluster_setup.asciidoc[]

== Understanding the Galera cluster synchronization

include::cluster/understanding_the_galera_cluster_synchronization.asciidoc[]

== Troubleshooting a cluster

include::cluster/troubleshooting_a_cluster.asciidoc[]

== Maintenance and Operations

include::cluster/maintenance_and_operations.asciidoc[]

== Layer 3 clusters

include::cluster/layer_3_clusters.asciidoc[]

== Advanced configuration

include::cluster/advanced_configuration.asciidoc[]


// INCLUDES

include::includes/additional-info.asciidoc[]

include::includes/commercial-support.asciidoc[]

include::includes/license.asciidoc[]

== Appendix

include::cluster/appendix.asciidoc[]
