PKI Quick Installation Guide
============================
:encoding: UTF-8
:lang: en
:doctype: book

include::includes/global-attributes.asciidoc[]

About this Guide
----------------

This guide has been created to give a quick start to install the Inverse PKI in PacketFence 5+. This guide does not include advanced troubleshooting of EAP-TLS connection. Refer to the documentation of EAP-TLS, RADIUS and OpenSSL for advanced features.

Assumptions
-----------

* You have at least one server with a fresh install of PacketFence 5+
* The server already have a switch with an 802.1X connection working
* RADIUS is fonctionnal for PEAP, EAP-TLS with your own certificate

Installation
------------

Step 1: Install the PKI
~~~~~~~~~~~~~~~~~~~~~~~

NOTE: Packetfence-PKI is avialable on the Packetfence repo as the package packetfence-pki. This is avialable for CentOS6 or Debian7.

Installing 
^^^^^^^^^^

First off you will need to install the package

Use the following command matching your OS.

Debian/Ubuntu:
 # sudo apt-get install packetfence-pki

CentOS/REHL:
 # yum install packetfence-pki

Step2: Configuring the PKI
~~~~~~~~~~~~~~~~~~~~~~~~~~

Inverse-PKI Configuration
^^^^^^^^^^^^^^^^^^^^^^^^^

NOTE: This following configuration will allow you to generate certificate for an EAP-TLS configuration, if you want to use the PKI for another purpose you will have to find the Key Usage/Extended Key Usage necessary.

Now that your PKI is installed, you need to configure it. A wizard is avialable @packetfence_management_ip:9191/pki

PKI Side
^^^^^^^^

You will first need to log into the PKI:

* Address: https://@server_ip:9191
* Login: admin
* Password: packetfence

After you logged in there is few steps to follow to have the PKI working for an EAP-TLS configuration with Packetfence. You will need to create the following items:

* Certificate of Authority
* Profiles(for each purpose, ie Server/Client auth are 2 different profiles)
* Manual certificate generation

To help you out trhough the configuration you just have to follow the wizard step to add a new CA.

Certificate of Authority
------------------------
 
* Key type, size and digest: we advise to use the following RSA, 2048, sha1
* Basic Constraints: CA:TRUE
* Key Usage and Extended Key Usage can be filled if necessary, more informations about Key Usage and Extended Key Usage here: rfc5280 part 4.2.1.3 and 4.2.1.12
* Days: Number of validity days, ie 3y = 1068

Profile
-------

Creation of a profile:

* Login: admin
* Password: packetfence
* Crl path: Certification revokation list path, a file will be created when you fill this.
* Validity: Number of validity days, ie 3y = 1068
* Key type, size and digest: we advise to use the following RSA, 2048, sha1
* Key Usage: Empty 
* Extended Key Usage: Server Certificate Authentication: TLS Web Server Authentication, Client Authentication: TLS Web Client Authentication, more informations about Key Usage and Extended Key Usage here: rfc5280 part 4.2.1.3 and 4.2.1.12
* The P12 mail setup is not mandatory but advise if you need to manually send certificate by email. This will format the mail send with your certificate. 

RADIUS server auth cert
-----------------------

Generate a certificate from the profile you defined as the server authentication Profile. This certificate will need to be installed and setup as the certificate for authenticate RADIUS. Also it will be necessary to install and trust the CA on Packetfence.

Client auth cert
----------------

Generate a certificate from the profile you defined as the client authentication Profile, if you generate this certificate manually you will need to use the 'download certificate' or 'send certificate' button. When the certificate is generate via Packetfence, the certificate is automatically integrate into the profile to setup the WiFi network.

Packetfence Side
^^^^^^^^^^^^^^^^

packetfence-pki
---------------

To work with our PKI in packetfence you will need to addi the PKI in the PKI_Provider section.

Click on add a new PKI and select packetfence-pki.

Follow the instructions below to fill the packetfence-pki configuration.

image::docs/images/Screenshot packetfence-pki 1/2[scaledwidth="100%",alt="SSID creation"]
image::docs/images/Screenshot packetfence-pki 2/2[scaledwidth="100%",alt="SSID creation"]

Additionnal informations
------------------------

If you need any additional information for the certificate generation we advise to go here: rfc 5280
