= Network Devices Configuration Guide
////

    This file is part of the PacketFence project.

    See includes/global-attributes.asciidoc
    for authors, copyright and license information.

////
include::includes/global-attributes.asciidoc[]

== About this Guide

This guide covers network device configuration for VLAN enforcement with PacketFence. Switches, wireless controllers and wireless access points are considered network devices in PacketFence.

Find the latest version at https://packetfence.org/documentation/

=== Other sources of information

<<PacketFence_Clustering_Guide.asciidoc#,Clustering Guide>>::
  Covers installation in a clustered environment.
<<PacketFence_Developers_Guide.asciidoc#,Developer's Guide>>::
  Covers API, captive portal customization, application code customizations and support for new equipment.
<<PacketFence_Installation_Guide.asciidoc#,Installation Guide>>::
  Covers installation and configuration of PacketFence.
<<PacketFence_Upgrade_Guide.asciidoc#,Upgrade Guide>>::
  Covers compatibility changes, manual instructions and upgrade notes.
https://packetfence.org/news.html[PacketFence News]::
  Covers noteworthy features, improvements and bug fixes by release.

Package and release tarballs include these files.

== Note on Inline enforcement support

Inline enforcement does not require this guide, except for RADIUS inline. RADIUS inline uses a flat layer-2 network on PacketFence's inline interface with no other gateway for Internet access.

Use this technique when network hardware does not support VLAN enforcement.

== Note on RADIUS accounting

Enabling RADIUS accounting on network devices significantly increases database size and may cause performance issues. Use RADIUS accounting only if absolutely required.

== List of supported Network Devices

include::network/list_of_supported_network_devices.asciidoc[]

== Switch configuration

include::network/switch_configuration.asciidoc[]

== Wireless Controllers and Access Point Configuration

include::network/wireless_controllers_and_access_point_configuration.asciidoc[]

== VPN Configuration

include::network/vpn_configuration.asciidoc[]

== Firewall Configuration

include::network/firewall_configuration.asciidoc[]

// INCLUDES

include::includes/additional-info.asciidoc[]

include::includes/commercial-support.asciidoc[]

include::includes/license.asciidoc[]


// vim: set syntax=asciidoc tabstop=2 shiftwidth=2 expandtab:
