---
- hosts: pfservers
  name: Prepare dot1x_eap_tls eapol_test (install and config) and radclient (install and config)
  become: True

  vars:
    # defaults file for wpasupplicant
    wpasupplicant__pkg_name: 'wpasupplicant'
    wpasupplicant__pkg_update_cache: 'no'
    wpasupplicant__conf_dir: '/etc/wpa_supplicant'
 
    wpasupplicant__service: 'wpa_supplicant'
    wpasupplicant__enabled: False
    wpasupplicant__state: stopped

    wpasupplicant__configs:
      - dir: '{{ wpasupplicant__conf_dir }}/eap_tls_scep'
        filename: 'eap_tls.conf'
      - dir: '{{ wpasupplicant__conf_dir }}/eap_tls_namual'
        filename: 'eap_tls.conf'
      - dir: '{{ wpasupplicant__conf_dir }}/eap_tls_pki'
        filename: 'eap_tls.conf'
      - dir: '{{ wpasupplicant__conf_dir }}/eap_peap'
        filename: 'eap_peap_mschapv2.conf'
      - dir: '{{ wpasupplicant__conf_dir }}/eap_ttls'
        filename: 'eap_ttls_pap.conf'

    ### eap_tls template variables
    wpasupplicant__eap_tls_identity: 'inverse'
    wpasupplicant__eap_tls_private_key_passwd: 'whatever'
    ### eap_peap_mschapv2 template variables
    wpasupplicant__eap_peap_mschapv2_identity: 'inverse'
    wpasupplicant__eap_peap_mschapv2_password: 'secret'
    ### eap_ttls_pap template variables
    wpasupplicant__eap_ttls_pap_identity: 'inverse'
    wpasupplicant__eap_ttls_pap_password: 'secret'


    eapol_test__pkg_name: "eapol_test"
    eapol_test__pkg_update_cache: 'no'

  tasks:
  - name: Install wpasupplicant
    include_tasks: ../../common/wpasupplicant.yml

  - name: deploy wpasupplicant config files
    include_tasks: ../../common/deploy_configs.yml
    loop: '{{ wpasupplicant__configs }}'

  - name: Install eapol_test
    include_tasks: ../../common/eapol_test.yml
