// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

//== Best Practices

=== IPTables

PacketFence manages IPTables entirely. For custom rules, create entries in
`/usr/local/pf/conf/iptables-custom.conf.inc` or modify
`/usr/local/pf/conf/iptables.conf.tt`. Default template works for most users.
More information available in Advanced topics -> Iptables.

=== Log Rotations

PacketFence generates many log entries in large production environments. Use
`logrotate` for periodic log rotation. A working logrotate script is provided in
`/etc/logrotate.d/` with daily rotation and compressed old logs. Added during
PacketFence installation.

=== Large Registration Network

Inline or VLAN enforcement in large environments may cause ARP table overflows
when many devices are on the same layer 2 segment. Symptoms include DHCP not
assigning IPs properly or failed pings in registration/quarantine VLANs. Check
`dmesg` log for `Neighbour table overflow` messages.

Mitigate by tweaking kernel settings. Enlarge ARP cache table by changing these
sysctl.conf values:

----
net.ipv4.neigh.default.gc_thresh1 = 2048
net.ipv4.neigh.default.gc_thresh2 = 4096
net.ipv4.neigh.default.gc_thresh3 = 8192
----

Enable changes as root:

[source,bash]
----
# sysctl -p
----

Layer 2 garbage collection starts at 2048 MAC addresses, with aggressive collection at 8192. This should suffice for most deployments - increase if needed (uses more kernel memory). Alternative solution: increase layer 2 network segmentation.



=== Active Directory fail-over

PacketFence authentication and authorization layers use 2 components for Active Directory 802.1x connections. Authentication: winbindd performs NTLM authentication for EAP-PEAP MSCHAPv2. Authorization: LDAP connections compute user roles. 
When using the captive portal or 802.1x authentication that doesn't rely on NTLM authentication (EAP-TLS, EAP-TTLS, etc), then only LDAP is used.

If you have multiple Active Directory servers, you must apply the following set of best practices to your installation so that PacketFence is able to efficiently detect a failure of one of your AD server and switch to the next one. This is even more important if your PacketFence deployment points to Active Directory servers located in 2 different availability zones (i.e. 2 different datacenters).

==== Authentication layer

To ensure the authentication layer will be able to fail-over efficiently, you must ensure that the 'Sticky DC' parameter of your domain configuration is set to `*`. Additionally, you must specify more than one DNS servers in that configuration. If you have more than one availability zone, then you must alternate the order of the servers. For example, if you have the following DNS servers in the first availability zone: `10.0.1.100,10.0.1.101` and the following in the second availability zone: `10.0.2.100,10.0.2.101`, then the DNS servers list should be: `10.0.1.100,10.0.2.100,10.0.1.101,10.0.2.101` which will ensure the second DNS server to be queried is part of a different availability zone than the first one when winbindd queries DNS to find an available Active Directory domain controller. 


===== Additional safety using monit

Some versions of samba/winbindd may not failover correctly when one of the DC fails, even with the best practices above. For this reason, it is suggested to enable monit on your installation. This will automatically activate an additional check that will restart winbindd if authentication fails to the current DC. Upon restart, a new DC will be found and authentication will resume. To enable this mecanism, enable monit as described <<_monit,in this section of the document>> and it be added automatically.

==== Authorization layer

The authorization layer of PacketFence uses the DNS servers setup on the operating system to resolve names. With that in mind, you will need to ensure that the servers in `/etc/resolv.conf` allow for proper fail-over should one of them fail. Similarly to the authentication layer, you must alternate the order of the servers based on the different availability zones you have. You will also want to have aggressive settings for fail-over to the next DNS server. For example, if you have the following DNS servers in the first availability zone: `10.0.1.100,10.0.1.101` and the following in the second availability zone: `10.0.2.100,10.0.2.101`, then the resulting `/etc/resolv.conf` should be:

----
search example.com

options timeout:1
options retries:1

nameserver 10.0.1.100
nameserver 10.0.2.100
nameserver 10.0.1.101
nameserver 10.0.2.101
----

Once the DNS servers of the OS are setup to fail-over efficiently, review the configuration of the different Active Directory sources you have in PacketFence (_Configuration -> Policies and Access Control -> Authentication Sources_). In these sources, you will need to ensure that you are either using a DNS name that resolves to multiple servers of your Active Directory domain or that multiple IP addresses are specified to connect. If you are not sure about the robustness of your DNS layer, use multiple IP addresses.

