// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

//== Installation

Install PacketFence using the Zero Effort NAC (ZEN) appliance or standard
package repository on GNU/Linux installations.

=== Installing PacketFence from the ZEN

ZEN (Zero Effort NAC) edition enables rapid PacketFence deployment. It's a fully
installed, preconfigured virtual appliance compatible with VMware ESX/ESXi,
Microsoft Hyper-V and other products. This section covers VMware-based
deployment. Xen-based hypervisors are not supported.

Download the ZEN here: https://www.packetfence.com/download/#zen

==== Virtual Machine

Tested with VMware ESXi, Fusion and Workstation with 16 GB RAM dedicated to the
VM. Compatible with other VMware products. Requires 64-bit CPU host for long
mode support. PacketFence ZEN comes as a pre-built OVF virtual disk. Import
the OVF using vSphere Client or vCenter for ESX hypervisors.

The VM's first network card receives IP through DHCP.

The virtual appliance passwords are:

.Management (Console/SSH) user
[options="compact"]
 * Login: root
 * Password: p@ck3tf3nc3

WARNING: Be sure to change default passwords if you plan to use this image in
production.

==== Import to ESX

Make sure that there is only one virtual network card created, and also make
sure that the vEthernet is connected to a virtual switch (vSwitch). That
virtual network card will be used as the PacketFence management interface.

==== Import to VMware Player/Workstation for Linux

Newer versions of VMware Player handle VLAN trunking a lot better. With that in
mind, we can use a single interface on the VM. So, ensure that the
VM host is plugged into a physical trunk port with VLAN 1,2,3,5,10 and 200 as
the allowed VLAN. These VLANs will be used later in configuration examples.

=== Installing PacketFence from the ISO

The ISO edition of PacketFence allows you to install PacketFence on Debian 12
with minimal effort. Instead of manually installing Debian 12 and installing
PacketFence after, this will perform both tasks and select the optimal
parameters and best practices for installing the operating system.

Download the ISO here:
https://www.packetfence.com/download/#packages

==== Machine specifications

This setup has been tested using VMware ESXi, Proxmox VE and VirtualBox and
works with any hypervisor PacketFence supports as well as bare-metal
servers.

A virtual machine or server with 16 GB of RAM dedicated to machine
as well as 4 CPUs is required. Allocate at least 200GB of disk space for
PacketFence.

==== Installing the ISO to a virtual machine

Provision a virtual machine with the specifications above, mount the ISO in the
CD/DVD drive of the machine and start it.
The installer will open. Follow the instructions on
screen to complete the installation.

==== Installing the ISO to a bare-metal server

First, ensure the server follows the specifications above, then burn the
ISO onto a DVD or USB key and boot it on the server.
The installer will open. Follow the instructions on
screen to complete the installation.

=== Installing PacketFence on existing Linux

PacketFence provides repositories for *RHEL 8* and *Debian 12* (bookworm) with
all required dependencies.

*Repository Benefits:*

[options="compact"]
 * Streamlined installation with dependency management
 * Pre-built RPM (EL8) and DEB (Debian 12) packages  
 * Simplified upgrade process

==== Common Prerequisites

*All Systems:*
[options="compact"]
 * Minimal OS installation (no additional packages)
 * UEFI Secure Boot *disabled* (if applicable)
 * System updated to latest patches
 * No SELinux or Apparmor enabled
 * No firewalld (Iptables is used)

==== RHEL 8 System Preparation

===== Security Configuration

[source,bash]
----
# Disable firewall and SELinux (required)
systemctl disable --now firewalld
sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config

# Update system
yum update

# Reboot to apply SELinux changes
reboot
----

PacketFence will not work properly if SELinux is enabled. Explicitly disable
SELinux in the `/etc/selinux/config` file and reboot the machine.

===== Kernel and Development Tools

*Prerequisites:*

[options="compact"]
 * Valid RHEL subscription for dependency installation
 * Latest kernel running

[source,bash]
----
# Install kernel development package for current kernel
yum install kernel-devel-$(uname -r)

# Remove conflicting container tools (PacketFence uses docker)
yum remove runc podman

# Import PacketFence GPG key (required for EL8)
rpm --import https://inverse.ca/downloads/GPG_PUBLIC_KEY
----

===== PacketFence Software Installation

[source,bash,subs="attributes"]
----
# Install PacketFence repository
yum localinstall https://www.packetfence.org/downloads/PacketFence/RHEL8/packetfence-release-{release_minor}.el8.noarch.rpm

# Install PacketFence with all dependencies
# Includes: MariaDB, FreeRADIUS, DHCP server
yum install --enablerepo=packetfence packetfence
----

==== Debian 12 System Preparation  

===== Security Configuration:
[source,bash]
----
# Update system first
apt-get update && apt-get upgrade

# Disable AppArmor (required)
systemctl disable --now apparmor
# Follow: https://wiki.debian.org/AppArmor/HowToUse#Disable_AppArmor

# Disable resolvconf and create static resolv.conf
rm /etc/resolv.conf
echo "nameserver 8.8.8.8" > /etc/resolv.conf

# Reboot to apply changes
reboot
----

Regarding AppArmor, even if they may be wanted by some organizations,
PacketFence will not work properly if AppArmor is enabled. Follow
instructions on the
link:https://wiki.debian.org/AppArmor/HowToUse#Disable_AppArmor[Debian wiki].

Regarding resolvconf, remove the symlink to that file and create the
`/etc/resolv.conf` file with the desired content.

===== Kernel and Development Tools

*Prerequisites:*

[options="compact"]
 * Fresh Debian 12 (bookworm) installation
 * Latest kernel running

[source,bash]
----
# Install kernel headers for current kernel
apt install linux-headers-$(uname -r)
----

*Important*: Ensure you're running the latest kernel before installing
development packages. Reboot if kernel was updated.

===== PacketFence Software Installation

[source,bash,subs="attributes"]  
----
# Install repository tools and GPG key
apt install gnupg sudo curl
curl -fsSL https://inverse.ca/downloads/GPG_PUBLIC_KEY | gpg --dearmor -o /etc/apt/keyrings/packetfence.gpg

# Add PacketFence repository (Debian 12 bookworm)
echo "deb [signed-by=/etc/apt/keyrings/packetfence.gpg] https://inverse.ca/downloads/PacketFence/debian/{release_minor} bookworm bookworm" > /etc/apt/sources.list.d/packetfence.list

# Install PacketFence with all dependencies  
# Includes: MariaDB, FreeRADIUS, DHCP server
apt-get update
apt-get install packetfence
----

=== Installing PacketFence on Linode

PacketFence v12 includes instructions on deploying PacketFence on Linode IaaS. See the <<#_how_to_deploy_packetfence_on_linode,Appendix>> below for details.
