// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

=== Kafka configuration

==== Setting the configuration for a standalone

To setup a Kafka standalone you need the following information.

Node ID, Hostname and IP address. (run the hostname command on the server,
packetfence is the example)

[options="compact"]
* hostname 172.16.3.1

The IP addressed of the clients (the server itself and the external IP
addresses)

[options="compact"]
* 172.16.3.1 (The server ip)

* 172.16.4.1 (An external IP)

Username of passwords

[options="compact"]
* admin: admin-pass

* user: pass

A unique cluster id which could be generated by the command below.

----
uuidgen | tr -d '-' | base64 | cut -b 1-22
----

Example

----
[packetfence]
KAFKA_NODE_ID=1
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.1:9094,EXTERNAL://172.16.1.100:9092,PF://100.64.0.1:9095,PFCONNECTOR://127.0.0.1:9096

[auth user]
pass=pass

[admin]
pass=admin-pass
user=admin

[iptables]
clients=172.16.3.1,172.16.4.1
cluster_ips=172.16.3.1

[cluster]
KAFKA_LOG_DIRS=/usr/local/pf/var/kafka
CLUSTER_ID=Y2I2MTdkMGNlMjI4NDUyMm
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,PF:PLAINTEXT,PFCONNECTOR:PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
KAFKA_LISTENERS=PF://0.0.0.0:9095,INTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092,PFCONNECTOR://0.0.0.0:9096
KAFKA_OPTS=-Djava.security.auth.login.config=/usr/local/pf/conf/kafka/kafka_server_jaas.conf
KAFKA_CONTROLLER_QUORUM_VOTERS=1@172.16.3.1:9093
KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
KAFKA_PROCESS_ROLES=broker,controller
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
----

==== Setting the configuration of the Kafka cluster

To setup a Kafka cluster you need the following information.

Node ID, Hostname and IP addresse, of each member.

[options="compact"]
* 1 hostname1 172.16.3.1

* 2 hostname2 172.16.3.2

* 3 hostname3 172.16.3.3

The IP addressed of the clients

[options="compact"]
* 172.16.4.1

* 172.16.4.2

Username of passwords

[options="compact"]
* admin: admin-pass

* user1: pass1

* user2: pass2

A unique cluster id which could be generated by the command below.

----
uuidgen | tr -d '-' | base64 | cut -b 1-22
----

Example
----

## Iptables rules

[iptables]
# The list of client
clients=172.16.4.1,172.16.4.2
# All the IP address of the cluster members
cluster_ips=172.16.3.1,172.16.3.2,172.16.3.3

#
[auth user1]
pass=pass1

[auth user2]
pass=pass2

#The Admin username and password
[admin]
user=admin
pass=admin-pass

#Global ENV variables
[cluster]
#The unique Cluster ID
CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
# List out each member using the following format <id>@<ip>:9093 comma separated
KAFKA_CONTROLLER_QUORUM_VOTERS=1@172.16.3.1:9093,2@172.16.3.2:9093,3@172.16.3.3:9093
KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,PF:PLAINTEXT
KAFKA_LISTENERS=PF://0.0.0.0:9095,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
KAFKA_LOG_DIRS=/usr/local/pf/var/kafka
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
KAFKA_OPTS=-Djava.security.auth.login.config=/usr/local/pf/conf/kafka/kafka_server_jaas.conf
KAFKA_PROCESS_ROLES=broker,controller
KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
...

##Member specific ENV variables
##List each cluster member using the following format
#[<hostname>]
#KAFKA_NODE_ID=<id>
#KAFKA_ADVERTISED_LISTENERS=INTERNAL://<ip>:29092,EXTERNAL://<ip>:9092
#
[hostname1]
KAFKA_NODE_ID=1
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.1:29092,EXTERNAL://172.16.3.1:9092,PF://100.64.0.1:9095

[hostname2]
KAFKA_NODE_ID=2
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.2:29092,EXTERNAL://172.16.3.2:9092,PF://100.64.0.1:9095

[hostname3]
KAFKA_NODE_ID=3
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.3:29092,EXTERNAL://172.16.3.3:9092,PF://100.64.0.1:9095

----

==== FingerBank collector kafka configuration

FingerBank collector can be configure to store the netflow sflow ipfix traffic
to Kafka in order to allow pfflow to compile it.

Here a sample of configuration that can be use with the Kafka server configured
above.

----
[collector]
additional_env=<<EOT
COLLECTOR_DISABLE_KAFKA=false
COLLECTOR_KAFKA_HOSTS=100.64.0.1:9095
COLLECTOR_DISABLE_IPFIX_SERVICE=false
COLLECTOR_DISABLE_SFLOW_KAFKA=false
COLLECTOR_KAFKA_USER=
COLLECTOR_KAFKA_PASS=
EOT
----

==== pfflow configuration

pfflow cron task can be configured to talk to kafka in order to compile the
netflow events to json payloads.


Here is the configuration that can be use in pfcron.conf to communicate with the
Kafka server configured above.

----
[pfflow]
#
# status
#
# If the task is enabled
status=enabled
#
# kafka_brokers
#
# Kafka Brokers to read from
kafka_brokers=100.64.0.1:9095
#
# uuid
#
# The UUID of the packetfence aggregator
uuid=f1e53295-c052-4602-a02f-8a6c90346c08
#
# kafka_user
#
# The Kafka username
kafka_user=
#
# kafka_pass
#
# The Kafka password
kafka_pass=
#
#filter_events=1
----

==== Restarting Services

----
systemctl restart packetfence-kafka
systemctl restart packetfence-fingerbank-collector
systemctl restart packetfence-pfcron
----

