// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

=== Kafka configuration

==== Setting the configuration for a standalone

To setup a Kafka standalone you need the following information.

Node ID, Hostname and IP address. (run the hostname command on the server,
packetfence is the example)

[options="compact"]
* hostname 172.16.3.1

The IP addresses of the clients (the server itself and the external IP
addresses)

[options="compact"]
* 172.16.3.1 (The server ip)

* 172.16.4.1 (An external IP)

Username and passwords

[options="compact"]
* admin: admin-pass

* user: pass

A unique cluster id which could be generated by the command below.

----
uuidgen | tr -d '-' | base64 | cut -b 1-22
----

Example

----
[packetfence]
KAFKA_NODE_ID=1
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.1:9094,EXTERNAL://172.16.1.100:9092,PF://100.64.0.1:9095,PFCONNECTOR://127.0.0.1:9096

[auth user]
pass=pass

[admin]
pass=admin-pass
user=admin

[iptables]
clients=172.16.3.1,172.16.4.1
cluster_ips=172.16.3.1

[cluster]
KAFKA_LOG_DIRS=/usr/local/pf/var/kafka
CLUSTER_ID=Y2I2MTdkMGNlMjI4NDUyMm
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,PF:PLAINTEXT,PFCONNECTOR:PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
KAFKA_LISTENERS=PF://0.0.0.0:9095,INTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092,PFCONNECTOR://0.0.0.0:9096
KAFKA_OPTS=-Djava.security.auth.login.config=/usr/local/pf/conf/kafka/kafka_server_jaas.conf
KAFKA_CONTROLLER_QUORUM_VOTERS=1@172.16.3.1:9093
KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
KAFKA_PROCESS_ROLES=broker,controller
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
----

==== Setting the configuration of the Kafka cluster

To setup a Kafka cluster you need the following information.

Node ID, Hostname and IP address, of each member.

[options="compact"]
* 1 hostname1 172.16.3.1

* 2 hostname2 172.16.3.2

* 3 hostname3 172.16.3.3

The IP addresses of the clients

[options="compact"]
* 172.16.4.1

* 172.16.4.2

Username of passwords

[options="compact"]
* admin: admin-pass

* user1: pass1

* user2: pass2

A unique cluster id which could be generated by the command below.

----
uuidgen | tr -d '-' | base64 | cut -b 1-22
----

Example
----

## Iptables rules

[iptables]
# The list of client
clients=172.16.4.1,172.16.4.2
# All the IP address of the cluster members
cluster_ips=172.16.3.1,172.16.3.2,172.16.3.3

#
[auth user1]
pass=pass1

[auth user2]
pass=pass2

#The Admin username and password
[admin]
user=admin
pass=admin-pass

#Global ENV variables
[cluster]
#The unique Cluster ID
CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
# List out each member using the following format <id>@<ip>:9093 comma separated
KAFKA_CONTROLLER_QUORUM_VOTERS=1@172.16.3.1:9093,2@172.16.3.2:9093,3@172.16.3.3:9093
KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,PF:PLAINTEXT
KAFKA_LISTENERS=PF://0.0.0.0:9095,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
KAFKA_LOG_DIRS=/usr/local/pf/var/kafka
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
KAFKA_OPTS=-Djava.security.auth.login.config=/usr/local/pf/conf/kafka/kafka_server_jaas.conf
KAFKA_PROCESS_ROLES=broker,controller
KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
...

##Member specific ENV variables
##List each cluster member using the following format
#[<hostname>]
#KAFKA_NODE_ID=<id>
#KAFKA_ADVERTISED_LISTENERS=INTERNAL://<ip>:29092,EXTERNAL://<ip>:9092
#
[hostname1]
KAFKA_NODE_ID=1
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.1:29092,EXTERNAL://172.16.3.1:9092,PF://100.64.0.1:9095

[hostname2]
KAFKA_NODE_ID=2
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.2:29092,EXTERNAL://172.16.3.2:9092,PF://100.64.0.1:9095

[hostname3]
KAFKA_NODE_ID=3
KAFKA_ADVERTISED_LISTENERS=INTERNAL://172.16.3.3:29092,EXTERNAL://172.16.3.3:9092,PF://100.64.0.1:9095

----

==== Securing the external listener with mTLS

The external Kafka listener (port 9092) can be secured with mutual TLS (mTLS)
using a broker certificate issued by the PacketFence PKI (pfpki). The internal
and inter-broker listeners are left unchanged. When mTLS is enabled, the
external listener switches to the `SSL` protocol and requires the connecting
client to present a certificate (`ssl.client.auth=required`).

===== Prerequisites

[options="compact"]
* A Certificate Authority configured in the PacketFence PKI that will sign the
  broker certificate.

* The PEM of the peer's CA certificate, i.e. the CA that signed the certificate
  of the client that connects to the broker. It is used to build the truststore
  so the broker can validate the client.

===== Initializing the keystore and truststore passwords

The keystore and truststore are PKCS12 files protected by passwords that are
generated automatically and stored in the `[ssl]` section of
`/usr/local/pf/conf/kafka.conf`. Generate them with:

----
/usr/local/pf/bin/kafka-init.pl
----

On a *cluster*, run this command on a *single* node only, then push the
configuration to the other members so that every node ends up with the same
`kafka.conf` (and therefore the same passwords):

----
/usr/local/pf/bin/cluster/sync --as-master
----

NOTE: Do not run `kafka-init.pl` on each member individually. It generates
random passwords, so running it on every node would produce a different password
per node, and the shared keystore distributed during certificate generation
would then fail to load on the other members.

===== Configuring mTLS in the administration interface

Go to *Configuration -> System Configuration -> Kafka* and, in the *mTLS*
section:

[options="compact"]
* *Enable mTLS*: turn it on.

* *Certificate Authority*: select the pfpki CA that will sign the broker
  certificate.

* *Common Name*: the CN of the broker certificate.

* *DNS Names* / *IP Addresses*: optional Subject Alternative Names for the broker
  certificate. In a cluster, the management IP of every member is added to the
  SANs automatically, so the single shared certificate is valid on all brokers.

* *Peer CA Certificate*: paste the PEM of the peer's CA certificate (the
  truststore used to validate the connecting client).

Save the form.

===== Generating the broker certificate

Click *Generate Certificate*. PacketFence issues the broker certificate from the
selected CA, writes the PEM material and the PKCS12 keystore and truststore under
`/usr/local/pf/conf/kafka/ssl`, and, in a cluster, distributes the keystore and
truststore to every member automatically.

Finally, restart the Kafka service on every node:

----
systemctl restart packetfence-kafka
----

===== Connecting a client with mTLS

The bundled `pfkafka` consumer can connect to the mTLS-secured listener using
the on-disk certificate material:

----
/usr/local/pf/bin/pfkafka -tls -broker <broker_ip>:9092 -topic pfflows_events
----

The `-cert`, `-key` and `-ca` options default to the artifacts under
`/usr/local/pf/conf/kafka/ssl` (`cert.pem`, `key.pem`, `ca.pem`); override them to
use a different client certificate. The client certificate must be signed by the
CA whose PEM was configured as the *Peer CA Certificate* above. Use
`-server-name` to override the name checked against the broker certificate when
connecting by IP.

==== FingerBank collector kafka configuration

FingerBank collector can be configured to store the NetFlow, sFlow, IPFIX traffic
to Kafka in order to allow pfflow to process it.

Here a sample of configuration that can be use with the Kafka server configured
above.

----
[collector]
additional_env=<<EOT
COLLECTOR_DISABLE_KAFKA=false
COLLECTOR_KAFKA_HOSTS=100.64.0.1:9095
COLLECTOR_DISABLE_IPFIX_SERVICE=false
COLLECTOR_DISABLE_SFLOW_KAFKA=false
COLLECTOR_KAFKA_USER=
COLLECTOR_KAFKA_PASS=
EOT
----

==== pfflow configuration

pfflow cron task can be configured to talk to kafka in order to compile the
netflow events to json payloads.


Here is the configuration that can be use in pfcron.conf to communicate with the
Kafka server configured above.

----
[pfflow]
#
# status
#
# If the task is enabled
status=enabled
#
# kafka_brokers
#
# Kafka Brokers to read from
kafka_brokers=100.64.0.1:9095
#
# uuid
#
# The UUID of the packetfence aggregator
uuid=f1e53295-c052-4602-a02f-8a6c90346c08
#
# kafka_user
#
# The Kafka username
kafka_user=
#
# kafka_pass
#
# The Kafka password
kafka_pass=
#
#filter_events=1
----

==== Restarting Services

----
systemctl restart packetfence-kafka
systemctl restart packetfence-fingerbank-collector
systemctl restart packetfence-pfcron
----

