// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

===== Monitoring with Netdata Cloud

PacketFence includes Netdata that is pre-installed and configured for most
use-cases.

The metrics are displayed in 2 separate sections

* Dashboard: This section displays the metrics collected by pfstats for the unregistration/registration status of all nodes managed by PacketFence.
* Monitoring: This section displays system metrics collected by Netdata for the local host (standalone), or all hosts in a cluster.

All metrics are retained for a maximum of 28 days. Older metrics are
automatically pruned to limit disk usage. To increase the retention rate edit
the configuration and restart the service:

[source,bash]
----
vi /usr/local/pf/conf/monitoring/netdata.conf

[db]
    retention = 2419200 # 28 days (seconds)
----

====== Dashboard

The dashboard diplays the metrics collected by pfstats for the
unregistration/registration status of all nodes managed by PacketFence. These
metrics are common across all cluster members, therefore a complete view is
displayed from any host that is a member of the same cluster.

[#netdata-cloud-dashboard-monitoring]
[NOTE]
====
Monitoring: The monitoring section displays the metrics collected by netdata for the health of the system. Wether the setup is standalone, or a cluster, a section is dedicated to each host in the deployment. When using one host to view metrics from another, the external host must be up and running.
====

The User Interface (Web Admin) now includes:

* A duration selection that can be used to zoom-in/zoom-out the timeline, up to a maximum of 28 days. If the retention rate is increased, these selections will remain the same.
* A "Netdata Cloud" button that opens a new window with the Netdata UI. Once launched the user can login anonymously (bottom-right), or the session_id can be used to attach the PacketFence instance to the Netdata Cloud.
* A zoom-able popup that displays and compares a single metric for all members in the cluster. Click any metric title to open this popup.

To obtain the local Netdata random session identifier:

[source,bash]
----
cat /usr/local/pf/var/netdata-lib/netdata_random_session_id
----

Once connected to Netdata Cloud, Netdata alerts will be sent to the email
address used to register the Netdata Cloud account.

To attach all members of a cluster, each member has its own unique session id;
where each must be used to login to Netdata Cloud manually.


===== Restarting Service

[source,bash]
----
systemctl restart packetfence-netdata
----
