// to display images directly on GitHub
ifdef::env-github[]
:encoding: UTF-8
:lang: en
:doctype: book
:toc: left
:imagesdir: ../../images
endif::[]

////

    This file is part of the PacketFence project.

    See PacketFence_Installation_Guide.asciidoc
    for authors, copyright and license information.

////

==== PacketFence Connector

NOTE:  The PacketFence Connector (pfconnector) is currently in the ‘Technical Preview’ phase. It can safely be used in production but has not yet been field proven for large scale and/or complex deployments

Starting from v12, PacketFence provides the PacketFence Connector. The PacketFence Connector allows you to establish a secure connection to a Cloud-hosted version of PacketFence so that NAS devices from a LAN can securely communicate with. The PacketFence Connector is meant to be lightweight, easy to configure and should not require any firewall changes as it tunnels everything over HTTPS.

Here are the use-cases the pfconnector supports:

 * RADIUS MAB
 * RADIUS 802.1X
 * Captive portal through Web Authentication (no registration or isolation VLAN support)
 * Performing access reevaluation through the pfconnector (i.e. RADIUS CoA/Disconnect, SNMP, etc)
 * Performing LDAP queries through the pfconnector to an on-premise LDAP server (including Active Directory) for portal and admin interface authentication
 * Authentication against a RADIUS source through the pfconnector to an on-premise RADIUS server for portal and admin interface authentication
 * Device profiling using the Fingerbank Collector (installed automatically with the pfconnector on 12.1+)

Current limitations:

 * The RADIUS secret used on your NAS devices must be the same as the secret in `/usr/local/pf/conf/local_secret`
 * The pfconnector cannot be used to connect PacketFence with an Active Directory for NTLM authentication

===== Installation

To deploy the PacketFence Connector, first provision on your local network (where NAS devices reside) a x86_64 Debian 12 virtual machine with minimal resources (2GB of RAM, 1 CPU core and 10GB of disk space). Then, perform the following commands as root:

[source,bash]
----
apt-get update
apt install gnupg sudo curl
curl -fsSL https://inverse.ca/downloads/GPG_PUBLIC_KEY | gpg --dearmor -o /etc/apt/keyrings/packetfence.gpg
----

Create a file named [filename]`/etc/apt/sources.list.d/packetfence-pfconnector-remote.list`:

// subs=attributes allow to substitute {release_minor} in code block
[source,bash,subs="attributes"]
----
echo "deb [signed-by=/etc/apt/keyrings/packetfence.gpg] http://inverse.ca/downloads/PacketFence/debian/{release_minor} bookworm bookworm" > \
/etc/apt/sources.list.d/packetfence-pfconnector-remote.list
----

Install and configure the connector

[source,bash,subs="attributes"]
----
apt update
apt install packetfence-pfconnector-remote
/usr/local/pfconnector-remote/bin/pfconnector-configure
----

When executing the last command, note down the Connector ID.

Then, from the PacketFence's admin interface, in the _Configuration->System Configuration->Connectors_ section, create a Connector with the ID from the last step. Then, generate a secret and add the networks where your network devices on remote sites are - this will be used for access reevaluation, SNMP communication, LDAP queries, etc.

Then, complete the PacketFence Connector configuration by specifying the secret and the host, which should be similar to:

----
https://NODE_BALANCER_IP:1443/api/v1/pfconnector/tunnel
----

If you configured a HTTP certificate signed by a public CA on PacketFence webadmin, you can answer `Yes` to the next question.

A configuration file will be created in [filename]`/usr/local/pfconnector-remote/conf/pfconnector-client.env`

Finally, restart the packetfence-pfconnector-remote service:

[source,bash]
----
systemctl restart packetfence-pfconnector-remote
----
   
Once your pfconnector is started, you can now point your network equipment to use the pfconnector's IP address for RADIUS and the captive portal like you would do with a typical on-premise PacketFence server. When defining the RADIUS secret in PacketFence and in your network equipment, always use the value inside `/usr/local/pf/conf/local_secret`.

===== Upgrade (for version prior to 12.1.0)

PacketFence Connector released with PacketFence 12.0.0 was not packaged.

In order to upgrade your PacketFence Connector to a packaged version, you need
to run following commands:

[source,bash]
----
apt-get update
apt install gnupg sudo curl
curl -fsSL https://inverse.ca/downloads/GPG_PUBLIC_KEY | gpg --dearmor -o /etc/apt/keyrings/packetfence.gpg
----

Create a file named [filename]`/etc/apt/sources.list.d/packetfence-pfconnector-remote.list`:

// subs=attributes allow to substitute {release_minor} in code block
[source,bash,subs="attributes"]
----
echo "deb [signed-by=/etc/apt/keyrings/packetfence.gpg] http://inverse.ca/downloads/PacketFence/debian/{release_minor} bookworm bookworm" > \
/etc/apt/sources.list.d/packetfence-pfconnector-remote.list
----


[source,bash,subs="attributes"]
----
apt update
apt install -y -o Dpkg::Options::="--force-confnew" packetfence-pfconnector-remote
----

The installation of `packetfence-pfconnector-remote` will remove your previous
installation and import your configuration.

Finally, restart the `packetfence-pfconnector-remote` service:

[source,bash]
----
systemctl restart packetfence-pfconnector-remote
----

===== Upgrade (for versions 12.1.0 and later)

In order to upgrade PacketFence Connector, you need to run following commands:

[source,bash]
----
apt-get update
apt install gnupg sudo curl
curl -fsSL https://inverse.ca/downloads/GPG_PUBLIC_KEY | gpg --dearmor -o /etc/apt/keyrings/packetfence.gpg
----

Create a file named [filename]`/etc/apt/sources.list.d/packetfence-pfconnector-remote.list`:

// subs=attributes allow to substitute {release_minor} in code block
[source,bash,subs="attributes"]
----
echo "deb [signed-by=/etc/apt/keyrings/packetfence.gpg] http://inverse.ca/downloads/PacketFence/debian/{release_minor} bookworm bookworm" > \
/etc/apt/sources.list.d/packetfence-pfconnector-remote.list
----

Upgrade

[source,bash,subs="attributes"]
----
apt update
apt upgrade
----

PacketFence Connector should have been restarted at end of the process. You can check its status using:

[source,bash]
----
systemctl status packetfence-pfconnector-remote
----

===== Static Ports

In cases where there needs be a static port where the packetfence host needs communicate to a service reserve the ports 30000-30999.

Currently these are defined for Radius Sources and DNS Connectors.
