# -*- mode: ruby -*-
# vi: set ft=ruby :

# Require YAML module
require 'yaml'
 
# Read YAML file with box details
inventory = YAML.load_file('inventory/hosts')
networks = inventory['all']['vars']['networks']

Vagrant.configure("2") do |config|
  # loop on **all** host(s) in linux_servers group in inventory to create VM(s)
  inventory['all']['children']['linux_servers']['hosts'].each do |server,details|
    config.vm.define server, autostart: false do |srv|
      srv.vm.box = details['box']
      srv.vm.hostname = server

      # mgmt
      # libvirt__forward_mode: "route" mean:
      # Allow inbound, but only to our expected subnet. Allow outbound, but
      # only from our expected subnet. Allow traffic between guests. Deny
      # all other inbound. Deny all other outbound.
      srv.vm.network "private_network",
                     :libvirt__network_name => networks[0]['name'],
                     :ip => details['mgmt_ip'],
                     :netmask => details['mgmt_netmask'],
                     :libvirt__dhcp_enabled => false,
                     :libvirt__forward_mode => networks[0]['forward_mode']

      srv.vm.provider "libvirt" do |v|
        v.cpus = details['cpus']
        v.memory = details['memory']
      end
    end
  end
end
