=head1 NAME

model_Config-Networks.t

=head1 DESCRIPTION

Unit testing for pfappserver::Model::Config::Networks

=cut
use strict;
use warnings;
use Test::More;

BEGIN { use_ok 'pfappserver::Model::Config::Networks' }

=head1 TESTS

=over

=item _load_networks_conf

=cut
# override default networks.conf file
$pf::config::network_config_file = 't/data/networks.conf';

my $networks_conf_ref = pfappserver::Model::Config::Networks->_load_networks_conf();

# generated by Data::Dumper
my $expected_conf_ref = {
            '10.102.0.0' => {
                              'netmask' => '255.255.0.0',
                              'gateway' => '10.102.0.1',
                              'domain-name' => 'vlan-registration.tests.packetfence.org',
                              'dns' => '10.102.0.1',
                              'dhcp_start' => '10.102.0.10',
                              'dhcp_end' => '10.102.255.246',
                              'dhcp_default_lease_time' => '300',
                              'dhcp_max_lease_time' => '600',
                              'type' => 'vlan-registration',
                              'named' => 'enabled',
                              'dhcpd' => 'enabled',
                              'pf_gateway' => '',
                              'next_hop' => ''
                            },
            '192.168.112.0' => {
                                 'netmask' => '255.255.255.0',
                                 'gateway' => '192.168.112.1',
                                 'domain-name' => 'vlan-registration.tests.packetfence.org',
                                 'dns' => '10.102.0.1',
                                 'dhcp_start' => '192.168.112.100',
                                 'dhcp_end' => '192.168.112.250',
                                 'dhcp_default_lease_time' => '300',
                                 'dhcp_max_lease_time' => '600',
                                 'type' => 'vlan-registration',
                                 'named' => 'enabled',
                                 'dhcpd' => 'enabled',
                                 'next_hop' => '10.0.0.1'
                               },
            '192.168.103.0' => {
                                 'netmask' => '255.255.255.0',
                                 'gateway' => '192.168.103.1',
                                 'domain-name' => 'vlan-isolation.tests.packetfence.org',
                                 'dns' => '192.168.103.1',
                                 'dhcp_start' => '192.168.103.10',
                                 'dhcp_end' => '192.168.103.246',
                                 'dhcp_default_lease_time' => '300',
                                 'dhcp_max_lease_time' => '600',
                                 'type' => 'vlan-isolation',
                                 'named' => 'enabled',
                                 'dhcpd' => 'enabled',
                                 'pf_gateway' => '',
                                 'next_hop' => ''
                               },
            '192.168.200.0' => {
                                 'dns' => '4.2.2.1',
                                 'dhcp_start' => '192.168.200.10',
                                 'gateway' => '192.168.200.1',
                                 'named' => 'enabled',
                                 'dhcpd' => 'enabled',
                                 'type' => 'inline',
                                 'netmask' => '255.255.255.0',
                                 'dhcp_end' => '192.168.200.246',
                                 'dhcp_default_lease_time' => '86400',
                                 'dhcp_max_lease_time' => '86400',
                                 'domain-name' => 'inline.tests.packetfence.org',
                                 'next_hop' => ''
                               }
};

is_deeply($networks_conf_ref, $expected_conf_ref, 'validating the networks.conf configuration parser');

done_testing();

=back

=head1 AUTHOR

Olivier Bilodeau <obilodeau@inverse.ca>

=head1 COPYRIGHT

Copyright (C) 2012 Inverse inc.

=head1 LICENSE

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
USA.

=cut

